### ISSUE TITLE
安装在SD卡时不支持Termux

### ISSUE THREAD

**Issue by Flyfish233** [android-hacker/VirtualXposed#100]
原因是Termux不能写入data分区。是否有方法重定向到VirtualXposed应用的data中？
![screenshot_20180501-220849](https://user-images.githubusercontent.com/37693645/39475973-ef5621d4-4d8c-11e8-8939-62093d699be8.png)
![screenshot_20180501-220926](https://user-images.githubusercontent.com/37693645/39475974-efaade4a-4d8c-11e8-8133-78b496f99791.png)
![screenshot_20180501-220902](https://user-images.githubusercontent.com/37693645/39475977-f035818a-4d8c-11e8-8197-58b96b2e89fe.png)

**Comment by tiann** [comment]
有办法，自己改代码。
