### ISSUE TITLE
微信下载文件闪退

### ISSUE THREAD

**Issue by xiaohuang2004** [android-hacker/VirtualXposed#101]
微信安装在VirtualXposed里面时，只要收到好友发送的稍微大一点的文件（基本上3M以上），下载到一半微信就会自动闪退，作者能不能解决一下这个问题。

**Comment by tiann** [comment]
fixed: https://github.com/android-hacker/VirtualXposed/commit/19df0839239fc8a9bfb273533f5c0e33ea220a4a
