### ISSUE TITLE
能否增加管理VirtualXposed内应用数据的功能？

### ISSUE THREAD

**Issue by jackyspy** [android-hacker/VirtualXposed#105]
在VirtualXposed内安装的应用程序，数据都放在VirtualXposed的数据目录中，能否提供这些应用数据访问修改的功能？

**Comment by tiann** [comment]
在内部装一个TotalCommander即可。https://www.bilibili.com/video/av20232338

**Comment by wordlesswind** [comment]
@tiann
那有没有方法修改文件权限，例如Terminal Emulator

**Comment by tiann** [comment]
@wordlesswind 内部的文件可以，还是用TotalCommander。

**Comment by wordlesswind** [comment]
@tiann
TotalCommander我点击属性直接未响应了
