### ISSUE TITLE
这个虚拟机性能和原生Xposed差别大吗?

### ISSUE THREAD

**Issue by androidcn** [android-hacker/VirtualXposed#108]
这个虚拟机性能和原生Xposed差别大吗?

**Comment by androidcn** [comment]
差别大就不折腾 Magisk 或者 Root Xposed了

**Comment by tiann** [comment]
先给结论：差别不大。

纠正一点，把这个叫做「虚拟机」并不合适。虚拟机一般会提供一个中间层，所有的代码执行，资源访问都是需要通过这个中间层；由于每做一件事都会多绕一下，所以性能不如原生系统是必然的。

VirtualApp的机制更类似于Docker，内部App的代码是直接运行在原生系统上的，在代码执行层面没有任何中间层（少许hook）；所以内部APP的性能与直接运行在系统上差距不大。（那VirtualApp做了什么呢？在内部APP与系统通信的过程中，做了拦截处理。这种通信过程通常是很少的，不会是性能问题的主要因素。）

如果非要说有，那也是因为VXP内部禁用了JIT（及时编译）；不过这部分你可以忽略不计，因为VXP内部APP安装的时候，全量编译了所有代码（空间换时间，占用磁盘空间会大一些），由于运行的都是机器码，AOT编译的QUICK CODE与JIT编译的code在绝大部分情况不会有差别。甚至，在Android N以上，刚刚安装使用的时候，VXP内部的APP会比原生系统更快（因为原生系统不会立马编译，需要用数次才会触发编译）。

**Comment by androidcn** [comment]
为何有这想法，因为微信太巨大，太慢，主要还是用微x模块，所以想问问性能影响
