### ISSUE TITLE
淘宝App无法清除数据

### ISSUE THREAD

**Issue by soeben** [android-hacker/VirtualXposed#109]
清除数据并使用应用变量重置全部参数并重启框架后淘宝的搜索记录依然存在，操作前后均未登陆，存储已重定向

**Comment by tiann** [comment]
手淘里面有个奇怪的文件 /cache/jsserver_crash/jsserver_crash_info.log  无法删除，之前VA的删除代码有问题，只要一个文件清除失败，整个目录就不再清除了。此bug已修复，但是无法删除的问题还需再研究。
