### ISSUE TITLE
三星S9 最新问题反馈。

### ISSUE THREAD

**Issue by kk99bb** [android-hacker/VirtualXposed#110]
机型：三星S9 港版（已刷国行）
系统：安卓8.0 真机未root 未装XP框架

问题1：VirtualXposed内双开微信，模块对分身微信无效果。比如装了微X模块，设置时自动进入微信1，不能进入分身微信设置。

问题2：VirtualXposed内微信指纹支付无法使用，尝试开启会提示：Failed to load generated key pair from keystore。

问题3：VirtualXposed内微信闪退，当聊天记录变多时闪退更频繁，几乎用不成。开启保守模式后，会好一些，但微X模块中的转发功能不能用了。

**Comment by tiann** [comment]
1. 本就不支持分身开模块，这是设定。
2. 我这没有S9 8.0的机器，你可以暂时用XP模块，指纹支付替代。
3. 要么等更新看看什么时候稳定了，要么开保守模式，要么用微信增强模块。
