### ISSUE TITLE
模拟器运行闪退问题

### ISSUE THREAD

**Issue by xhyin1208** [android-hacker/VirtualXposed#113]
你好，在逍遥模拟器上调试时，如果编译了x86的库，ES文件管理器能运行，如果只编译了arm的库，ES文件管理器闪退。不知道大神碰到这个问题没有？有办法可以解决吗？

**Comment by tiann** [comment]
不支持x86，用arm模拟器即可。#47

**Comment by xhyin1208** [comment]
现在模拟器都有x86和arm两套指令吧，只有arm库的可以直接装在模拟器上，但是在vpx上运行就闪退。现在没有做兼容的计划？

**Comment by tiann** [comment]
没有
