### ISSUE TITLE
[功能建议]数据的备份和恢复

### ISSUE THREAD

**Issue by hhuimie** [android-hacker/VirtualXposed#114]
非常希望有备份和恢复的功能.
如果是用total commander, 可以复制出来, 但是不能覆盖进去. 可能是我操作有误.
不过如果大佬能把这个功能列入需求内就更好了.
非常感谢大佬!

**Comment by tiann** [comment]
可以复制进去

**Comment by hhuimie** [comment]
@tiann 大佬可不可以说下, 是覆盖/data/data/io.va.exposed下的所有内容吗? 要改权限什么的吗?

**Comment by tiann** [comment]
/data/data/io.va.exposed/virtual/user/0/<你要恢复的APP包名>

**Comment by hhuimie** [comment]
@tiann 非常感谢大佬~~~

**Comment by hhuimie** [comment]
@tiann 又试了一下, 复制进去的时候, 一直是这画面, 取消了之后, 有文件夹, 但是文件夹里没文件

![20180509215935](https://user-images.githubusercontent.com/4830177/39818954-bcbeeafa-53d4-11e8-8e2b-62c01facede8.jpg)

**Comment by hhuimie** [comment]
@tiann 一样, 复制不进去
![20180509224557](https://user-images.githubusercontent.com/4830177/39821448-dafc6186-53da-11e8-9492-121dbceeb27d.jpg)

**Comment by tiann** [comment]
设置-高级设置-文件复制功能呢？

**Comment by hhuimie** [comment]
可以, 但是有点麻烦了.
真的非常希望弄一个备份复制的功能.
就算是默认备份所有的文件就好~
多谢了大佬

**Comment by fxsheep** [comment]
@tiann 可以弄个备份整个环境为.tar.gz 或从备份导入的功能吗？有的时候在没root的情况下导数据很麻烦
