### ISSUE TITLE
Android P 闪退

### ISSUE THREAD

**Issue by Vegas7** [android-hacker/VirtualXposed#115]
Android P 闪退

**Comment by tiann** [comment]
现在才DP2，等P发布了再说。

**Comment by Tabll** [comment]
遇到了同样的问题

**Comment by androidcn** [comment]
现阶段 DP2 肯定 不给你修Bug,等吧

**Comment by mapleshadow** [comment]
其实修修无妨啊，迟早要修的。。。。。。

**Comment by case3526** [comment]
支持楼上

**Comment by oasisfeng** [comment]
@tiann API 已经 final 了。趁现在先测试兼容性，如果是 P 的 bug 及早提 issue；如果是 hidden API block，更要尽早提交解禁申述。等到 P 发布（其实基本上 DP 4就定版了）就一切晚矣...

**Comment by tiann** [comment]
谢谢冯老师的建议。之前我看过Android P的闪退，是访问hidden API导致的。但是VA里面这种case太多了，google不可能把这些都解禁掉。因此我的想法是在运行时直接修改runtime(DP2上修改一个 ART 的flag就可以)，绕过对hidden API的验证，我测试过这样是行得通的。不过我不清楚验证hidden API这一块后续会不会有改动，因此一直处于观望状态。

**Comment by oasisfeng** [comment]
@asLody 对 VirtualApp 有何打算？按照 @tiann 的思路，我担心这种 trick 迟早被 Google 以安全漏洞为由封堵，更糟糕的可能性是被 Google Play Protect 当作 malware，那样用户就会恐慌了。

**Comment by Tabll** [comment]
刚刚在第三个安卓9.0测试版中测试过，程序是可以正常运行了
只是不能克隆和安装应用，提示无法解析安装包

**Comment by tiann** [comment]
@oasisfeng 事实上VA内部也用了好多这种trick，我觉得只能一条路走到黑。。

**Comment by tiann** [comment]
@Tabll 这是因为P上PackageParser的接口变了，需要适配。还有一些反射的API都发生了变化，比如ActivityThread中的部分类。

**Comment by tiann** [comment]
我绕过非SDK接口的方法在这里：https://github.com/tiann/FreeReflection

不过昨天公布之后，小米的开发哥哥说他要打个补丁把这玩意儿修复掉，然后upload给aosp，目测要完。。
所以还是等Android P正式发布之后再说吧，这样好歹能苟延残喘一个版本 😅

**Comment by tiann** [comment]
fixed : https://github.com/android-hacker/VirtualXposed/releases/tag/0.12.9
