### ISSUE TITLE
請为Android X86設备提供支持

### ISSUE THREAD

**Issue by vsex7** [android-hacker/VirtualXposed#116]
#Android模擬器#android emulator #blissrom #jide remix #Phoenix OS

**Comment by tiann** [comment]
绝大部分用户应该不会用到 X86的设备吧？

**Comment by addhaloka** [comment]
请注意很多app在x86模拟器上无法运行并不是vxp支持x86能解决的

**Comment by Enyby** [comment]
![scr_1526183062](https://user-images.githubusercontent.com/1543372/39963605-37a6a59a-5679-11e8-8a48-0e47e4835364.jpg)

**Comment by tiann** [comment]
@Enyby It is the distribution of GameGuardian, the user group of it is special (May be lots of Emulator).

All the way, the main goal of VirtualXposed is to use Xposed Module without root, I even do not enough time to do this satisfactory.

**Comment by tiann** [comment]
Hi there, I add partial support for x86, https://github.com/android-hacker/VirtualXposed/commit/930af579770b50ef58a1a4c8633bfd5314cd1715

You can not install it in x86 devices, but Xposed may not work correctly.

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/releases/tag/0.10.0
