### ISSUE TITLE
基于VirtualApp打开其他应用，退出后Activity黑屏，出现ANR

### ISSUE THREAD

**Issue by gam2046** [android-hacker/VirtualXposed#119]
恳求获得开发者帮助，我clone了一份VirtualApp的代码，进行简单包装后，希望测试一下可用性，但是我发现所有应用正常退出后都会停留在VirtualApp的Stub Activity上，然后出现ANR。

VirtualXposed项目，一开始是否有这样的情况出现？

**Comment by tiann** [comment]
没有
