### ISSUE TITLE
这是抄袭的么  lody

### ISSUE THREAD

**Issue by qianyukun** [android-hacker/VirtualXposed#12]

**Comment by tiann** [comment]
请把readme读完再来提issue，谢谢。

**Comment by qianyukun** [comment]
对lody的东西还是比较熟悉，看到你的东西对他的修改不大，就有了联想  ^_^ 莫生气

**Comment by tiann** [comment]
VirtualXposed 分为四部分：
Java hook库epic，Xposed兼容层 exposed，主界面launcher，VirtualApp。

其中，前三部分并不在这个项目里面，而是以依赖的形式引入；所以你会觉得没做什么修改。

**Comment by asLody** [comment]
哈哈，莫激动

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
