### ISSUE TITLE
 多份克隆，其他程序识别不了

### ISSUE THREAD

**Issue by waxwax0099** [android-hacker/VirtualXposed#120]
比如我对同一个程序克隆两份，我装的应用变量，app setting之类的程序，列表里都看不见第2份克隆。
请问这是框架问题吗？

**Comment by tiann** [comment]
设定问题，只允许一个应用生效。

**Comment by waxwax0099** [comment]
这个设定，是指VXP的设定？
我刚又试了下，克隆了两份DevCheck，在VXP里装的ES浏览器只能看见第一份克隆。

**Comment by tiann** [comment]
VXP的设定
