### ISSUE TITLE
请问能否加强对内部应用的通知的管理？

### ISSUE THREAD

**Issue by wordlesswind** [android-hacker/VirtualXposed#122]
比如某个应用的通知不想开启，然后通知可以分门别类的发送。
这点应该可以参照
https://github.com/Trumeet/MiPushFramework/
它的那个Push可以做到分门别类的发送每个应用的通知。

**Comment by tiann** [comment]
这个软件的目的不是做一个完善的双开软件，暂时没空做这个。
