### ISSUE TITLE
請问有办法支持“钉钉”不

### ISSUE THREAD

**Issue by TheoShira** [android-hacker/VirtualXposed#123]
现在安装钉钉后提示非官方版本，请问这个有办法解决不？

**Comment by tiann** [comment]
找钉钉Xposed插件的作者，绕过检测即可。VirtualXposed 本身不会做这件事。

**Comment by TheoShira** [comment]
可是之所以提示非官方版本 是因为被安装在模拟器里的原因（在多开软件都会这样）， 和xposed插件应该没有关系，无论手机有没有ROOT或安装xposed插件，只要是在本机安装就不会提示这个问题

**Comment by tiann** [comment]
可以通过Xposed插件绕过。
