### ISSUE TITLE
English too broken

### ISSUE THREAD

**Issue by TacoTheDank** [android-hacker/VirtualXposed#124]
"<string name="meizu_device_tips_content">In Meizu OS, You can only use VirtualXposed by clone App; please install XposedInstaller first.</string>"

I can't seem to figure out what this is supposed to say, can any of you help me out here? xd

**Comment by tiann** [comment]
I am sorry, this means that Meizu's device can not add apps to VirtualXposed by choosing apk file in sdcard, it must install the app to system first, and then clone it to VirtualXposed, in addition, VirtualXposed doesn't have build-in Xposed Installer in Meizu OS, users must install it manully.

There is a Chinese wiki: https://github.com/android-hacker/VirtualXposed/wiki/Usage-for-Flyme

**Comment by TacoTheDank** [comment]
ah ok
