### ISSUE TITLE
oppoA59s打开微信，一直是opening

### ISSUE THREAD

**Issue by xq598359628** [android-hacker/VirtualXposed#13]
先试了我的华为荣耀ok，接着用oppo测试，系统5.1，打开微信后如题

**Comment by tiann** [comment]
系统版本，color os版本是多少？

**Comment by ncxnbrwa** [comment]
我华为荣耀8,打开微信巫师一直是opening状态

**Comment by oO0oO0oO0o0o00** [comment]
既然也是微信的问题就不单开issue了。

- 启用微X模块后，微信和QQ无法打开，另一款叫BlockSecureFlag的xp模块也无法打开了，该模块用于取消禁止截图。
- 禁用微X模块就都可以打开。
- QX模块同样造成该问题。
- 外部的xposed，QQ微信和这些模块都能正常使用。
- 系统6.0，EMUI 4.1

**Comment by tiann** [comment]
@ncxnbrwa 微信巫师用 2.5.5 版本试下

**Comment by tiann** [comment]
no feedback, close.
