### ISSUE TITLE
静态广播接收器无法接收广播

### ISSUE THREAD

**Issue by niceLaoShiJi** [android-hacker/VirtualXposed#132]
xirtualxposed运行包含静态注册广播接收器的apk，静态注册接收器无法接收广播，包括自定义的广播和系统广播

**Comment by niceLaoShiJi** [comment]
在app未启动前，静态注册广播接收器收不到广播， app启动后就可以收到。在多种机型测试后，发现是小米系统的原因。

**Comment by tiann** [comment]
静态广播手动加名单就可以让内部APP收到，自己改代码即可。
