### ISSUE TITLE
ProxyDroid在virtualxposed运行

### ISSUE THREAD

**Issue by niceLaoShiJi** [android-hacker/VirtualXposed#135]
能否让virtualxposed支持ProxyDroid， 原理上是否可行？

**Comment by tiann** [comment]
直接在外面开代理不就行了吗？

**Comment by niceLaoShiJi** [comment]
系统的是普通的http/https代理，我想开sock5代理，因为很多app现在不走http/https代理。如果在外面开，还是得把android root， 就没有使用virtualxposed的意义了。

**Comment by tiann** [comment]
看了 DroidProxy的实现原理，在VXP里这么做是行不通的。

不过可以用另外的方式支持，比如VXP自己开VPNService，然后代理掉内部APP的VPN。你可以尝试一下，但是我不会花时间去做这个。
