### ISSUE TITLE
网易云音乐问题

### ISSUE THREAD

**Issue by Moniga** [android-hacker/VirtualXposed#136]
网易云音乐使用音量增强感觉不太稳定。会卡屏 ，还有听一段时间之后（大概10多分钟）会自动停止播放。（VirtualXposed已加入电池白名单，所有权限均给予）
手机  荣耀9
系统  安卓8.1
求大佬解决

**Comment by tiann** [comment]
华为系统自己的内存清理白名单之类的加了吗？

**Comment by Moniga** [comment]
都加了……所有要的权限都给了

**Comment by Smoovsky** [comment]
P20 PRO也有类似的问题
启动网易云音乐的时候有概率闪退，音乐播放几分钟后可能会退出。
剩下就是流畅度有些捉急……

**Comment by tiann** [comment]
duplicate #78

**Comment by drcege** [comment]
这个问题没有解决啊…… 听一会歌就会自动暂停了。

准确的说是没声音了，程序还在，网易云进度显示还在播放，就是声音被掐断了

**Comment by haibugouing** [comment]
最新版本、S9+、8.0同样问题，没有音量加强，官方最新，不出25分钟必停

**Comment by allen0091** [comment]
最新版本 android 9 网易云 4.3.1 同樣問題 高機率閃退
