### ISSUE TITLE
Publish virtual xposed on f-droid?

### ISSUE THREAD

**Issue by xpirad** [android-hacker/VirtualXposed#137]
Wish you could publish this app on f-droid.

This will make update easier/safer and expose it to a wider audience.

Please consider it, thank you!

**Comment by tiann** [comment]
Thank you for your advice, but i can not do that because of the License of https://github.com/asLody/VirtualApp

**Comment by linsui** [comment]
#138 
[VirtualXposed](https://gitlab.com/IzzyOnDroid/repo/issues/15)
[New App: VirtualXposed](https://gitlab.com/fdroid/rfp/issues/807)

By the links above, I guess the license problem has been solved, so could you change the readme? And will you provide a build [without Crashlytics](https://gitlab.com/fdroid/rfp/issues/807#note_119249003)? I really hope this great app can be published in F-Droid.

**Comment by tiann** [comment]
@linsui Thanks for your advice, i will do it ASAP.

**Comment by licaon-kter** [comment]
@tiann Any thoughts? Ref: https://f-droid.org/wiki/page/io.va.exposed/lastbuild_174

**Comment by tiann** [comment]
I forgot to upload the `exposed-core:0.7.7-c` to jcenter, please try it again.

In fact, you can compile https://github.com/android-hacker/exposed to get the correct dependency.
