### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by IzzySoft** [android-hacker/VirtualXposed#138]
Could you please state what license your app is covered by? Thanks in advance!

**Comment by tiann** [comment]
I am sorry, because of https://github.com/asLody/VirtualApp, the License of VirtualXposed is "No License"

**Comment by IzzySoft** [comment]
That's sad, as that way one is always unclear what's permitted and what not. Nevertheless: might I suggest you add that fact to the end of the `README.md` (e.g. at the very end after "Credits")?

Further, [I've been asked](https://gitlab.com/IzzyOnDroid/repo/issues/15) to provide your app [via my repo](https://apt.izzysoft.de/fdroid/repo) (as the official F-Droid repo most likely won't accept it without license). I'm considering that, if you agree – and if modules *not* working are rather the exception (not the other way around). Explanation for the latter: on a first glance it looks like only a few specific modules are supported, and those are rather focused on a specific geographic region (e.g. Baidu, WeChat etc suggest "Chinese only" – especially as that part is written in Chinese). Could you please clarify?

Thanks a lot!

**Comment by tiann** [comment]
Thank you for your advice, I will add the fact to the end of `README.md`

To be specific, I use a library named [VirtualApp](https://github.com/asLody/VirtualApp), It was GPL3 License before, but it delete the license in 2017/10/29.

The module supported by VirtualXposed is far more than the list in `README.md`, in fact, the list is modules I used and tested myself(I am a Chinese, so the modules are mostly developed by Chinese :). There may be many modules that can be used which i do not know.

**Comment by tiann** [comment]
Maybe i can make a fork in https://github.com/asLody/VirtualApp/commit/00f152f98a922ced0d858c31e1a9c2f0afb53ab6

and keep VirtualXposed GPL3?

**Comment by IzzySoft** [comment]
Thanks again, tiann! That makes things much clearer. I was afraid you had to explicitly add adjustments for each module to work.

So now I'm perfectly willing to provide your app via my repo (as indicated above) – and will include some of your explanations with the description. May I suggest you also add to your Readme:

* rename the section "supported modules" to "modules tested by myself"
* add the text "The only two restrictions …" (from your above comment) to the "Introduction" section

That would help avoiding "future confusion" a little :wink:

As for the license: I'm no expert here. If you can put a license like GPL-3.0, that would of course be great. Maybe clarify that with "upstream"?

**Comment by tiann** [comment]
OK, Thank you very much, lzzySoft!

I am on the train now, and I will fix all of these after my holiday :)

**Comment by k3b** [comment]
From https://github.com/android-hacker/VirtualXposed/README.md 

> Usage for Commercial Purposes are not allowed!!! 

If i understood https://www.gnu.org/licenses/gpl-faq.html#NoMilitary correctly 
this restriction may be not compatible with gpl:

>   More generally, a license that limits who can use a program, or for what, is not a free software license.

**Comment by tiann** [comment]
It is not GPL license.

**Comment by IzzySoft** [comment]
> More generally, a license that limits who can use a program, or for what, is not a free software license.

That might satisfy the letter – but I still wouldn't want my work used for warfare. Freedom should respect life – and not include a "freedom to kill". You should be free to decide how you live – but not how I die. So I'm not happy with that GNU.org phrasing/interpretation. Looks like I need to reconsider my choice of license. Unfortunately, CC-BY-NC-SA is not considered a software license …

**Comment by k3b** [comment]
if you use the lib "VirtualApp" as of 2017-10-29 as gpl3 then the app must must be compatible with GPL3.  

> Usage for Commercial Purposes are not allowed

is not compatible with gpl3.

> but I still wouldn't want my work used for warfare.
> ...
> So I'm not happy with that GNU.org phrasing/interpretation.

I totally agree.

**Comment by ttimasdf** [comment]
@k3b @lzzySoft It's a warfare between Chinese. Some ot them just do not respect any licences and agreements. There's already been some derivatives of VirtualApp in the market. That's why the author remove the license and make it closed sourced. If @tiann is kindly enough to maintain a fork, I suggest we make no Chinese docs and descriptions available.

**Comment by tiann** [comment]
There is nothing to do with Chinese.

**Comment by tiann** [comment]
Hi there, The README has modified.

I opened a new branch [license](https://github.com/android-hacker/VirtualXposed/tree/license) to match the GPLv3 License, but it seems has a lot of work to do(so many conflict to merge)

It may take a while.

**Comment by TPS** [comment]
@tiann Sorry about all the extra work to make this right! 🙇 (I'm the 1 who started this whole event, I guess, by filing the original [RFP](https://gitlab.com/IzzyOnDroid/repo/issues/15). 😳)

**Comment by tiann** [comment]
@TPS Thank you for your work!! 

Although there are extra work to do, it is worth doing doing that.

**Comment by tiann** [comment]
Hi, there, after took a lot of effort, I have merge all my commit to the branch:

https://github.com/android-hacker/VirtualXposed/tree/license

But this branch is much less stable than the `exposed` branch, the forked branch which stay GPLv3 doesn't contain some important fixes of VirtualApp (I will try to fix it).

**Comment by TPS** [comment]
What's the best way to build the GPL branch? (Could you provide a build flavor?)  I see leaving non-GPL branch @IzzySoft's repo (whaddya think, @IzzySoft) & adding RFP for GPL branch @ F-Droid, just as long both have simultaneous progress from this point onwards.

Will that be too much, @tiann? :worried:

**Comment by IzzySoft** [comment]
I've set the license to GPLv3 now according to the post made by @tiann (hope that's correct). Will you merge that up, or what is the issue?

**Comment by tiann** [comment]
Sorry, I am working on support of Google Service in VirtualXposed in the last few days.

The `license` branch of VirtualXposed is unstable now, new release (0.11.5) is still in `exposed` branch.

**Comment by IzzySoft** [comment]
What I meant was I picked the APK from here and added it to my repo, declaring the license GPLv3. Then I've noticed that it seems like GPLv3 is only valid for that branch. Will master be adopting GPLv3 as well in the near future?

**Comment by IzzySoft** [comment]
Mind to decide before the bot is closing this issue? :wink:

**Comment by theScrabi** [comment]
@tiann I contributed several apps to fdroid, and I know that they sometimes add apps that are not 100% free. There is a small chance.

Now I know that VirtualApp is not FreeSoftware (but OpenSource), and therefore it is a little tricky to enable GPLv3 for the app. However @tiann I highly recomend you to add a GPL or  a mandatory license anyway. Many apps such as [Wire](https://github.com/wireapp/wire) do something similar, since they are FLOSS, but use GSM services.

If you made the license clear it could improve community acceptance, and that would boost your project ;D

**Comment by tiann** [comment]
I have made a new branch `vxp`, it is based on https://github.com/asLody/VirtualApp/commit/00f152f98a922ced0d858c31e1a9c2f0afb53ab6

Is it GPL3 compatible? How do you think?

**Comment by IzzySoft** [comment]
As you've closed this, @tiann: what licencse did you decide on? I still can't see any.

**Comment by tiann** [comment]
@IzzySoft I have made `vxp` the default branch, it is GPL3 now: https://github.com/android-hacker/VirtualXposed/blob/vxp/LICENSE.txt

**Comment by IzzySoft** [comment]
Ah, now it shows – thanks!
