### ISSUE TITLE
微信启动卡在黑屏，在线等

### ISSUE THREAD

**Issue by meetinnet** [android-hacker/VirtualXposed#139]
。。。。。。。

第一次遇到这个情况，一般闪退或者卡住，重启vxp或者强行结束再开就解决。
这次无论如何进不去了，一打开微信，就卡在黑屏界面，只能看到通知栏，也可以下拉，但就是进不去。
开启和关闭保守模式都试过，结束vxp任务，重启vxp也试过，重启手机也试过。
再不知道怎么办了，清除数据没试过，记录还没保存啊。

荣耀V10，安卓8，微信6.6.6.

**Comment by meetinnet** [comment]
应用管理里面的修复功能也试过。

**Comment by tiann** [comment]
插件都关了呢？

**Comment by meetinnet** [comment]
所有插件都关了，xpose里面的全部去掉勾选了。
顺便请问一下，微信聊天记录在vxp里面是都保存在VirtualXposed\vsdcard\1\tencent\MicroMsg下面吗，对应原版微信的\data\data\com.tencent.mm\MicriMsg 是在哪呢？
多谢。

**Comment by tiann** [comment]
在 /data/data/io.va.exposed/virtual/data/user/0/com.tencent.mm/MicroMsg 下，你可以（备份之后）尝试删除这个目录，看看能否恢复。

**Comment by meetinnet** [comment]
卸载重装了，记录都没了。

聊天记录不在VirtualXposed\vsdcard\1\tencent\MicroMsg里面，悲伤。

**Comment by meetinnet** [comment]
没有root，进不去那个文件夹。：（

**Comment by tiann** [comment]
在里面装totoalcommander可以访问

**Comment by meetinnet** [comment]
访问不了，那个“文件系统根目录” 点击之后提示“错误：无法打开文件或文件夹”

**Comment by tiann** [comment]
文件系统根目录是肯定没法访问的。

关于如何访问内部文件，可以看我之前做的视频：https://www.bilibili.com/video/av20232338
