### ISSUE TITLE
网易云音乐无法播放音乐

### ISSUE THREAD

**Issue by bergyu** [android-hacker/VirtualXposed#14]
之前的版本0.73没问题，今天更新了以后，更新说明有sd重定向，结果网易云音乐一播放音乐就闪退，清楚网易云音乐数据也是闪退，一加3氢7.1的系统

**Comment by tiann** [comment]
fixed： https://github.com/android-hacker/VirtualXposed/commit/3feee9e8bf974560c55cb9932b2afb731cebbed4

可以去设置－应用管理 中关闭存储重定向。
