### ISSUE TITLE
无法在virtual xposed中启动任何VPN连接

### ISSUE THREAD

**Issue by Letisl** [android-hacker/VirtualXposed#142]
手机:redmi 5 plus
系统:7.1.2
软件:0.9.9

问题:在virtual xposed中无法启动任何VPN，会在屏幕下方提示是否允许建立VPN连接，但是点击确定后仍无法启动，状态栏无钥匙标志，软件显示与点击启动VPN之前相同。

**Comment by tiann** [comment]
duplicated #62 

在外面开VPN即可。
