### ISSUE TITLE
can't completely remove virtualxposed

### ISSUE THREAD

**Issue by herr-carl** [android-hacker/VirtualXposed#144]
Hello,

my google play protect keep poping up the message, that virtualxposed may harm my phone, even I uninstalled it and no signs of it in app list.
is there anything I can do to remove it completely?

Thanks.

**Comment by tiann** [comment]
Uninstall it and remove /sdcard/VirtualXposed/

**Comment by herr-carl** [comment]
Thanks. Found an empty directory in internal storage and deleted.

Will report again if the message emerged for another time.

**Comment by tiann** [comment]
VirtualXposed is a ordinary App, it can not modify private file system. Maybe this is a bug of system Uninstaller.

**Comment by herr-carl** [comment]
The problem remains.

It said "The app can add charges to your mobile bill by sending costly SMS messages without informing you first." I have hit uninstall in the pop-up window and check app list. It should be completely removed but this annoying window keep reminding me.

Is there any residue after uninstalling that I should take care about?

**Comment by herr-carl** [comment]
[https://imgur.com/a/1FYGHMQ](url)
The screenbshot of google protect's warning.

**Comment by tiann** [comment]
This can not be bug of VirtualXposed(A normal app can not do that), check your system uninstaller.

Because VirtulalXposed must hold all permission the inner app needs,  it ask for a lot of permissions, this is necessary, it can not be resolved.
