### ISSUE TITLE
0.9.9下载安装应用变量后启动qq黑屏卡住

### ISSUE THREAD

**Issue by bhui** [android-hacker/VirtualXposed#145]
从常用模块里面下载的应用变量，在virtualxposed里面启动应用变量时提示 xposed貌似没有工作... 请前往模块重新勾选应用变量，重新启动。照做之后现象仍然是一样的。
机型:红米note3 
android版本：5.0.2  MIUI9.5 稳定版
qq 版本：7.6.0
你们的运行正常吗？

**Comment by tiann** [comment]
MIUI 升级一下系统试试呢？（比如 Android 6.0/7.0) 现在5.0的太少了，几乎没测试过，可能有问题。

**Comment by tiann** [comment]
inactive close.
