### ISSUE TITLE
你好，腾讯游戏 使用微信登陆出现问题

### ISSUE THREAD

**Issue by IrohFt** [android-hacker/VirtualXposed#146]
你好，问题现象，把游戏（天天爱消除）添加进框架内，然后在框架里面启动天天爱消除，然后使用点击微信登陆会弹出微信授权但是授权结束后没有返回应用，而是会重新在框架外部开启一个新的游戏，关闭外面的游戏 后，框架内部的游戏还是没有登陆的情况

**Comment by IrohFt** [comment]
我试着把应用[龙珠直播]加入框架后，也无法使用微信进行登陆，表现：能拉起外部微信，微信授权后 不会像游戏 一样在外部打开应用而是会返回登陆页面但是无法登陆成功

**Comment by tiann** [comment]
把微信装里面

**Comment by IrohFt** [comment]
@tiann 您好，我有试的，把微信也装里面可以正常登陆及使用，只是会把外部的微信账号t下线，有没有办法处理这个问题？QQ登陆是可以正常使用外部QQ授权的，非常感谢您的回复！

**Comment by tiann** [comment]
没办法

**Comment by IrohFt** [comment]
哦，好的，感谢您的回复 @tiann
