### ISSUE TITLE
魅族MX5 FLYME6 框架克隆安装后，无法激活。

### ISSUE THREAD

**Issue by 007genius** [android-hacker/VirtualXposed#147]
![s80522-213841](https://user-images.githubusercontent.com/38709086/40366004-acf21622-5e08-11e8-9460-1f74066ed447.jpg)

**Comment by tiann** [comment]
加群，安装魅族专版XP。

**Comment by ocean143** [comment]
按照wiki里面的下载了xp的3.1.5，在vitualxposed里面打开一直都是转菊花
