### ISSUE TITLE
运行后无法调试模块

### ISSUE THREAD

**Issue by qssq** [android-hacker/VirtualXposed#150]
我尝试断点了几个进程都没反应，我开发root 的xposed都可以调试的，难道我还是搞错进程了么？

**Comment by qssq** [comment]
其实我想手动把/data/data/virtualposed/virtual/data/data/xxx/复制到另外一个xxx下的。现在调试都如此困难。。

**Comment by qssq** [comment]
不知道这机制禁止操作，，想有没有通过file 复制功能，操作虚拟空间所有app数据。

**Comment by tiann** [comment]
这两天搬家，抱歉这么晚才回复。

调试的话，可以用这个版本：https://github.com/android-hacker/VirtualXposed/releases/download/0.9.9/VirtualXposed_0.9.9_for_GameGuardian.apk

（这个版本debug开关是开的）

**Comment by qssq** [comment]
我root机，都可以调试的，是ve进程吗？但是搞不懂这个调试进程没反应。

**Comment by tiann** [comment]
如果你root了，改了 ro.debuggable 那应该都是可以的；实在不行，就用我上面传的那个包，对手机没要求。
