### ISSUE TITLE
所有APP需要输入调用键盘的时候闪退

### ISSUE THREAD

**Issue by shanligang1017** [android-hacker/VirtualXposed#151]
visualxposed版本： 0.99
手机版本：一加5T 安卓8.1

突然发现所有的APP要输入东西的地方点一下都闪退，应该是调用键盘有啥问题吧，不知道有没有办法解决

**Comment by tiann** [comment]
突然发现，就是说之前不闪退？现在闪退了，还是一直如此？

**Comment by shanligang1017** [comment]
之前好像是可以的，不知道什么时候不可以了，已经忘记中间有没有升级过系统，不过升级也是小版本，而且我双清后还是不行

**Comment by tiann** [comment]
那可能是升级的这个系统不兼容，不过我没有对应的机器测试。

**Comment by shanligang1017** [comment]
嗯嗯算了，这个机型太小众了，刚好要换mix2s，不管他了，谢谢回复
