### ISSUE TITLE
坚果pro2 Xposed所有模块不工作

### ISSUE THREAD

**Issue by yizhichaye** [android-hacker/VirtualXposed#152]
坚果pro2
smartisan os v4.2.1
android 7.1.1
按照教程，在VX中安装好微信和Xposed，Xposed 安装了微信增强模块，且重启了VX；
VX 中微信打开后，尝试使用微信增强模块中的功能，但是，不成功，不知道什么问题；

**Comment by Moniga** [comment]
把vxp保守模式关了就可以用微信增强的功能了

**Comment by tiann** [comment]
如果保守模式开启，没问题了我就close了。
