### ISSUE TITLE
Creating inbuilt root

### ISSUE THREAD

**Issue by prathamb** [android-hacker/VirtualXposed#158]
I just have an idea of it's possible please create an inbuilt root option, so that we can use apps that need root through virtualxposed , 
Thanks

**Comment by tiann** [comment]
This is impossible.

If I can get root, why do I create Virtualxposed？just root your device and install Xposed is simplest.

Please understand what is the meaning of root permission.

**Comment by prathamb** [comment]
Sorry , good luck and thanks for your development :)

**Comment by prathamb** [comment]
And any plan or idea will it support good service in future ?
