### ISSUE TITLE
How to build with different package name?

### ISSUE THREAD

**Issue by psycholyzern** [android-hacker/VirtualXposed#161]
Hi. I want to build this app with different package name for some reason. Is there any easy way? I Googled and the tutorial doesnt match the folder structure. In tutorials,   psckage name `com.some.thing` would have folder structure `/com/some/thing`. Your app is `io.va.exposed`, but source have `/io/virtualapp`.

**Comment by tiann** [comment]
package name and application id is not same concept.

**Comment by psycholyzern** [comment]
Hi @tiann. I am sorry, I don't know about these. Could you help me? It is ok if you can't, I'l ask help on another place.

I found that this app is useful for me not because can run xposed modules, but because it is has a virtual space. I believe traffic from apps installed inside it recognized as VirtualXposed itself. It is useful because I can run many apps and the system will recognize their traffic as one.
I want to spoof apps and bypass internet restriction. Any help would be appreciated. Thanks.
