### ISSUE TITLE
gameguardian 守护进程无法启动

### ISSUE THREAD

**Issue by guoleifei** [android-hacker/VirtualXposed#162]
![image](https://user-images.githubusercontent.com/16201257/40529564-11747fba-6028-11e8-87d3-d015dd5baee9.png)
gameguardian 运行守护进程无法启动 无法选择应用进程

**Comment by tiann** [comment]
用这个：https://github.com/android-hacker/VirtualXposed/releases/download/0.9.9/VirtualXposed_0.9.9_for_GameGuardian.apk

**Comment by guoleifei** [comment]
我用的就是这个。。。 我重新安装了你发的链接下载的这个版本还是会出现这个问题。我的手机是S7edge

**Comment by tiann** [comment]
8.0不支持。

**Comment by guoleifei** [comment]
我的是7.0.。

**Comment by tiann** [comment]
GG版本是多少？

**Comment by guoleifei** [comment]
8.58.0

**Comment by tiann** [comment]
那我就不知道了，可能是三星不支持吧

**Comment by guoleifei** [comment]
但是游戏可以。。运行 估计是gameguardian 不支持吧。。。

**Comment by guoleifei** [comment]
其他的修改可以使用么

**Comment by tiann** [comment]
自己试，VXP主要目的不是做这个。
