### ISSUE TITLE
坚果r1，无法模拟定位

### ISSUE THREAD

**Issue by KimDong** [android-hacker/VirtualXposed#163]
试了三个应用，包括摩拜单车app，一直提示要打开gps。即使不安装任何插件也无法获取定位

**Comment by tiann** [comment]
请详细描述你的问题，包括但不局限于机型，系统版本，VXP版本，Xposed插件版本。

**Comment by KimDong** [comment]
坚果r1，系统6.0.1.1，安卓版本8.1，vxp0.9.9，摩拜单车app7.4.1。在vxp中安装app，打开app提示要求开启gps定位功能。然后我尝试开启存储重定向后，打开app可获取当前定位了。然后我安装模拟位置插件1.2.681，无法模拟
