### ISSUE TITLE
網易雲 黑畫面

### ISSUE THREAD

**Issue by kai456789** [android-hacker/VirtualXposed#164]
VAEXPOSED升級後 網易雲 能開啟 但只要點擊任何操作 就會變黑畫面

按返回 就會跳回原本畫面 無法操作

**Comment by tiann** [comment]
请详细描述你的问题，包括但不局限于机型，系统版本，VXP版本，Xposed插件版本。

**Comment by tiann** [comment]
duplicate #78

**Comment by kai456789** [comment]
VAEXPOSED 0.99 三星S7E 安卓7.0版本 
沒裝插件 只裝網易雲 開啟正常 但只要 點擊任一功能 就會黑畫面

**Comment by tiann** [comment]
fixed： https://github.com/android-hacker/exposed/commit/dfcf21cccaefc35f83be17eb91f3872d68427701
