### ISSUE TITLE
建议Virtual Xposed注册为启动器launcher

### ISSUE THREAD

**Issue by kikandychan** [android-hacker/VirtualXposed#166]
如果想快速启动xposed里的app，只能通过创建桌面快捷方式的方式，如果app多了，大多数自然喜欢到抽屉里找，如果virtualXposed是启动器，这些安装在vxposed里的app可以直接在抽屉里，操作方式上滑打开抽屉，Vxposed里的app和android系统的app并列显示，操作更加原生，不知道我的建议可否被采纳。

**Comment by tiann** [comment]
可以做到，但是不会做。

其一，VirtualXposed永远取代不了原生桌面，外面的APP无法通过 VXP启动。强行兼容原生桌面会带来无穷无尽的工作量。
其二，做一个产品得清楚自己的定位，VXP的目的不是做桌面。
