### ISSUE TITLE
如何调出VirtualXposed默认的APK安装器...

### ISSUE THREAD

**Issue by meetinnet** [android-hacker/VirtualXposed#168]
。。
今天安装程序的时候点快了，选了系统安装，并选择了“总是”的按钮，结果再一次安装程序就不弹出VirtualXposed的APK安装器了，进VXP高级设置里面开关开关开关了好几次那个“禁用VirtualXposed的APK安装器”，安装程序的时候还是不弹选择框，直接就默认系统安装了。

请问这个在哪能调出来呢，荣耀V10。

多谢。

**Comment by tiann** [comment]
系统应用里面找到 软件安装程序 清楚默认设置即可。
