### ISSUE TITLE
Daemon is not working since i update my phone to oreo pls fix it virtualxposed version 0.9.9

### ISSUE THREAD

**Issue by Guntur541** [android-hacker/VirtualXposed#169]
how to fix it pls help me

**Comment by tiann** [comment]
GameGuardian ?

Oreo is not supported.

**Comment by Guntur541** [comment]
really?

**Comment by Guntur541** [comment]
so sad

**Comment by tiann** [comment]
It's a limit of System, and google won't fix it: https://issuetracker.google.com/issues/37140047

**Comment by tiann** [comment]
https://github.com/termux/termux-app/issues/299

**Comment by ghost** [comment]
it worked after reinstalling
