### ISSUE TITLE
小米6 miui9 8.3.8 virtualxposed 0.8.3 一起走专业版app打不开

### ISSUE THREAD

**Issue by wu4258528** [android-hacker/VirtualXposed#17]
一起走app配合运动修改器使用，在一加3的xposed下是没问题的。在virtualxposed里一起走app打开时opening要显示十几秒，然后就黑屏没反应了。。。virtualxposed里的微信等应用也不稳定，还卡，现在基本都是用360的分身大事x版开微信，不过广告太多了。。。

**Comment by tiann** [comment]
所有软件都不行的话，是不是开了某个不兼容的插件，或者装的是内测版/开发版的ROM。

我的MIX 2 S MIUI 9，Android 8.0，一切正常。
