### ISSUE TITLE
多个Module只会Hook第一个

### ISSUE THREAD

**Issue by EricMo** [android-hacker/VirtualXposed#170]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

在`assets/xposed_init`的文件中使用多个Module会出现只hook第一个Module

## 复现步骤
在
`assets/xposed_init`
中插入多个模块，并且每个都hook不同的进程【也就是不同的应用】，然后会出现只hook第一个的情况。
情况一：
```
com.xxxxx.MainModule（主hook）
com.xxxxx.SelfModule（副hook）
```
情况二：
```
com.xxxxx.SelfModule（副hook）
com.xxxxx.MainModule（主hook）
```
主hook:用来做正常hook
副hook用来hook自身应用，更改激活状态
情况一的时候主hook成功，xposed日志显示`Loading class com.xxxxx.MainModule`
情况二的时候副hook成功，xposed日志显示`Loading class com.xxxxx.SelfModule`

## 环境

机型：小米Mix2s
系统版本：Android 8.0
ROM版本：稳定版
Xposed 插件以及插件版本：91 api:82
VirtualXposed版本：0.9.9

**Comment by tiann** [comment]
谢谢反馈，下版本会解决掉。

**Comment by tiann** [comment]
fixed: https://github.com/android-hacker/exposed/commit/f4b2e4251c6830def11309365f464285007a2a70

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/releases/tag/0.10.0
