### ISSUE TITLE
老问题，希望能解决魅族下xposed未激活的问题

### ISSUE THREAD

**Issue by tobarcn** [android-hacker/VirtualXposed#173]
查了一圈，只找到一个关闭了的issue，提到加群获得魅族专版安装器，但是找不到任何关于群的信息

希望能提供下载地址到wiki的Flyme使用方法中

**Comment by tiann** [comment]
已修改：https://github.com/android-hacker/VirtualXposed/wiki/%E9%AD%85%E6%97%8F%E7%B3%BB%E7%BB%9F%E7%9A%84%E9%97%AE%E9%A2%98
