### ISSUE TITLE
非桌面模式

### ISSUE THREAD

**Issue by cslcslcsl** [android-hacker/VirtualXposed#176]
目的
更优雅的使用安卓手机；

简介
首页
打开app后是一个应用列表，而不是桌面，然后添加需要框架优化的应用；

应用排序
时间升序降序，名称升序降序；

批量操作
批量移除应用；

快捷方式
发送经框架优化后的应用快捷方式至系统桌面，支持启动；

应用独立
克隆原有应用后，删除原有应用仍可以启动克隆后的应用；

简便更新
安装新版应用后，自动克隆新版（可选）；
注：将老版本克隆后删除，克隆的老版本是可以独立运行的，这时，系统安装新版本，仍可以自动克隆；

原型
https://pro.modao.cc/app/HV04OWiIlOJLuSS5hS8eeBHAZFxvNfv

最后
真心希望此款应用发扬光大，为不能root的用户造福！
需要产品专业上的帮助可以联系我c735855649@gmail.com；

**Comment by tiann** [comment]
谢谢建议还有你的原型图。不过我是这样想的，

最开始的时候，VirtualXposed 就是类似于你的这种方式，不过是网格而不是列表。如果应用比较少，这样做确实简洁明了。但是，如果在里面装50个应用，操作成本就非常非常高了。首先我得想到我要打开的是什么应用，然后他的名字拼音是啥，然后通过一个很长的列表滚动到对应的地方。

思考了很久，我觉得我遇到的问题跟系统的Launcher是一样的。用了Launcher之后，可以把图标随意摆放，打开APP可以依靠肌肉记忆。如果打开比较少用的APP，直接用搜索功能。因此，我才模仿着做了一个虚拟桌面。

你可以尝试一下在里面装一堆应用，一定会体会到我说的那种痛苦的。然后，虚拟桌面是可以放图标的，拖到上面即可；而且，虚拟桌面还可以放好几页:

![image](https://user-images.githubusercontent.com/4233744/40762861-05fd0cae-64d5-11e8-8329-ec68a3363519.png)

**Comment by fxsheep** [comment]
那可不可以克隆一个系统自带桌面出来，pixel launcher有时候用不惯

**Comment by tiann** [comment]
不行的哦，这个桌面与VXP的用户系统是耦合的；克隆出来的应用权限不够。
