### ISSUE TITLE
非常感谢您的付出让我们可以用到这么优秀的软件

### ISSUE THREAD

**Issue by AcAugus** [android-hacker/VirtualXposed#177]
感谢这个项目所有参与者和您的付出让其得以完善，并帮助到这么多的人，目前还是学生没有办法提供足够多的捐助，所以在这里表示感谢。
此外有一个功能上的建议，就是希望如果作者有空，可以在储存卡重定向这个功能上加一个批量重定向或者说是提示哪些应用已经是打开重定向的，否则需要手动一个一个点开去看实在是否有打开重定向功能，有点麻烦。
另外个人觉得应用目录可以做成直接显示图标而不用↑划的可能更加方便，至于桌面设置和添加应用则改成双指或者其他方式触发。希望作者可以考虑！！再次感谢

**Comment by tiann** [comment]
谢谢。

1. 重定向这个功能并不常用，不会在这上面花精力了。
2. 应用可以把图标拖到虚拟桌面上，这样不用上滑。
3. 可以长按桌面空白处，触发添加应用和设置的功能。
