### ISSUE TITLE
小米6 Android 8.0 MIUI 9.5稳定版 装了VirtualXposed后 手机自身无法安装应用了

### ISSUE THREAD

**Issue by magical-xu** [android-hacker/VirtualXposed#178]
## 问题描述

手机本身安装不了应用了，提示“没有找到应用打开该类型的文件”
自带的应用商店可以安装，应用宝、酷安或网上下载的apk安装不了，卸了VirtualXposed也不行，重启手机也不行

## 环境

机型： 小米6
系统版本： 8.0
ROM版本：MIUI 9.5 稳定版
VirtualXposed版本：0.10.1

**Comment by tiann** [comment]
没太明白具体啥意思

**Comment by magical-xu** [comment]
就是我装了VirtualXposed的apk后 可以在该应用里面 克隆app或选择文件中apk进行安装
但是原本手机里 只有小米应用商店可以正常下载安装apk 
别的app比如 应用宝、酷安啥的都不能安装apk了 ，浏览器下载的也不行

**Comment by tiann** [comment]
设置-高级设置-禁用VirtualXposed的apk安装器打开看看是否解决问题

**Comment by magical-xu** [comment]
无法安装到系统
禁用VirtuaXposed apk安装器也无效 就好像手机坏了一样

**Comment by magical-xu** [comment]
![20180531_194857](https://user-images.githubusercontent.com/15309220/40780696-dc84acb0-650b-11e8-9ae0-ea0b8ca2d2cd.gif)
传了个图

**Comment by tiann** [comment]
MIUI出现过多次这种问题，应该与VXP无关，

http://bbs.xiaomi.cn/t-12633392-2-o1#comment_top
http://www.miui.com/thread-3687839-1-1.html

可以尝试下：设置-其它应用管理-默认应用设置-恢复默认，试试

**Comment by magical-xu** [comment]
好吧 我试了下用 ES文件管理器 可以安装 先这样吧 感谢大佬回复
