### ISSUE TITLE
不能使用 WX 框架 出现 VirtualXposed已经停止

### ISSUE THREAD

**Issue by QianBianMiao** [android-hacker/VirtualXposed#179]
## 问题描述
不能使用 微X 框架
安装后激活 微X 框架 出现 VirtualXposed 已经停止
打开 微信 出现 VirtualXposed 已经停止

## 复现步骤

不能使用 微X 框架 安装完毕 微X框架 并在框架中开启后 进入 微X 设置会出现 VirtualXposed 已经停止  也无法启动微信程序 （我反复试用了很多微信版本都无法解决）  微X是最新的版本 1.21

## 环境

机型：三星 NOTE EDGE
系统版本：6.0.1
ROM版本：官方
Xposed 插件以及插件版本：
VirtualXposed版本：0.10.1

## 补充

我怀疑 微X 有可能是不是屏蔽了 VirtualXposed 为什么打开就崩？

**Comment by tiann** [comment]
升级到 7.0试试

**Comment by zhangjianying** [comment]
android 8.1 红米note5 miui10 使用微X也是奔溃

**Comment by tiann** [comment]
用最新版 0.12.1 试下。
PS：崩溃个一两次是正常的
