### ISSUE TITLE
EMUI 4.0.1 添加WX打开闪退到桌面

### ISSUE THREAD

**Issue by freesd** [android-hacker/VirtualXposed#19]
基于android 6.0 的EMUI,添加微信后，打开之后闪退，其它程序也是一样，系统安装有XPOSED 88.2版本，希望能支持EMUI ROM.

**Comment by tiann** [comment]
系统已经安装Xposed，不要再VXP内开启任何插件（实际上插件是生效的）重复开启会加载两次，有冲突。
