### ISSUE TITLE
Device ID/MAC/IMEI...

### ISSUE THREAD

**Issue by NoFear1183** [android-hacker/VirtualXposed#194]
Is it possible to add manual settings for device information. So if I remove an app or game, and then add it again, I can do a different "device". And where can I do this manually?  (I have root). Thanks for your hard work and impressive app. Keep it up :)

-NoFear

**Comment by tiann** [comment]
This Xposed module can help you do this: [AppEnv](https://github.com/kingsollyu/AppEnv-Kotlin/releases)

**Comment by NoFear1183** [comment]
Thank you for the reply and help.
