### ISSUE TITLE
三星6.0系统QQ通知栏收不到消息

### ISSUE THREAD

**Issue by xinyangslove** [android-hacker/VirtualXposed#196]
## 问题描述

我添加的应用 qq和微信，别人发消息的时候 通知栏和快捷方式图标右上角均无小红点通知.是需要设置么？ 还是bug？
默认安装virtuaxposed状态下,然后添加了qq和微信，微信版本6.6.6，qq版本6.6.7，然后创建到桌面快捷方式，目前微信可以通知栏收到通知，qq通知栏收不到，然后快捷方式右上角也没有通知.

## 复现步骤
默认安装virtuaxposed状态下，只添加了qq和微信

## 环境

机型：
系统版本：android6.0.1
ROM版本：三星s7 edge MMB29m.
Xposed 插件以及插件版本：无
VirtualXposed版本：0.10.1

**Comment by tiann** [comment]
快捷方式右上角不会有原点，这个没法解决。

QQ通知栏没有消息说下具体情况。
