### ISSUE TITLE
ThreadGroup is parent for self

### ISSUE THREAD

**Issue by Enyby** [android-hacker/VirtualXposed#199]
**Describe the bug**
Root ThreadGroup must return null as parent. But it return self.

**To Reproduce**
```
Log.w(TAG, "START");
ThreadGroup root = Thread.currentThread().getThreadGroup();
while (root.getParent() != null) {
	ThreadGroup parent = root.getParent();
	if (parent == root) {
		Log.w(TAG, "ERROR: " + root + " == " + parent);
		break;
	}
    root = parent;
}
Log.w(TAG, "END");
```

**Expected behavior**
```
START
END
```
But I get next:
```
START
ERROR: com.lody.virtual.client.VClientImpl$RootThreadGroup[name=VA-Root,maxpri=10] == com.lody.virtual.client.VClientImpl$RootThreadGroup[name=VA-Root,maxpri=10]
END
```
So any code like this:
```
ThreadGroup root = Thread.currentThread().getThreadGroup();
while (root.getParent() != null) {
    root = root.getParent();
}
```
Fall into endless loop.
For example here:
https://github.com/android-hacker/VirtualXposed/blob/170524ae1600ab3abd78a7377e4355892f6fbe31/VirtualApp/lib/src/main/java/com/lody/virtual/client/VClientImpl.java#L412

**Smartphone (please complete the following information):**
 - Android 7.0.0 x86 Genymotion emulator
But I do not think this only for x86 or for Android 7.0.0

**Additional context**
I think issue in this code:
https://github.com/android-hacker/VirtualXposed/blob/170524ae1600ab3abd78a7377e4355892f6fbe31/VirtualApp/lib/src/main/java/com/lody/virtual/client/VClientImpl.java#L411
Possible it is firmware related issue.
In any case need prevent set as parent self.

**Comment by Enyby** [comment]
I try check code in firmware in boot.oat for ThreadGroup implementation, but it is look like as in AOSP. parent is final field, set only in constructor. getParent is final method and return field.
Possible VairtualApp has some hooks for getParent.

**Comment by Enyby** [comment]
```
try {
	Log.w(TAG, "START");
	ThreadGroup root = Thread.currentThread().getThreadGroup();
    while (root.getParent() != null) {
    	ThreadGroup parent = root.getParent();
    	if (parent == root) {
    		Field f = ThreadGroup.class.getDeclaredField("parent");
    		Log.w(TAG, "Field: " + f);
    		f.setAccessible(true);
    		Object o = f.get(root);
    		Log.w(TAG, "Value: " + o);
    		
    		Method m = root.getClass().getMethod("getParent");
    		Log.w(TAG, "Method 1: " + m);
    		
    		m = ThreadGroup.class.getDeclaredMethod("getParent");
    		Log.w(TAG, "Method 2: " + m);
    		
    		Log.w(TAG, "ERROR: " + root + " == " + parent);
    		break;
    	}
        root = parent;
    }
    Log.w(TAG, "END");
} catch (Throwable e) {
	Log.w(TAG, "EXCEPTION", e);
}
```

```
START
Field: private final java.lang.ThreadGroup java.lang.ThreadGroup.parent
Value: com.lody.virtual.client.VClientImpl$RootThreadGroup[name=VA-Root,maxpri=10]
Method 1: public final java.lang.ThreadGroup java.lang.ThreadGroup.getParent()
Method 2: public final java.lang.ThreadGroup java.lang.ThreadGroup.getParent()
ERROR: com.lody.virtual.client.VClientImpl$RootThreadGroup[name=VA-Root,maxpri=10] == com.lody.virtual.client.VClientImpl$RootThreadGroup[name=VA-Ro

END
```
It is loo like impossible. Final field must be set in constructor. 
So it can be set from null to same object via reflection or jni.

**Comment by Enyby** [comment]
Possible need add check here:
https://github.com/android-hacker/VirtualXposed/blob/170524ae1600ab3abd78a7377e4355892f6fbe31/VirtualApp/lib/src/main/java/com/lody/virtual/client/VClientImpl.java#L428
and here:
https://github.com/android-hacker/VirtualXposed/blob/170524ae1600ab3abd78a7377e4355892f6fbe31/VirtualApp/lib/src/main/java/com/lody/virtual/client/VClientImpl.java#L439
```
if (group != newRoot)
```
Possible need other corrections.
Maybe need make push request to original VirtualApp repo.

I do not understand this code very well so I do not create push request/

**Comment by tiann** [comment]
thank you, i will fix It soon

**Comment by tiann** [comment]
I have tested it on Android Oreo MR1 device, i think it will work on all devices, thank you for your detailed information 👍
