### ISSUE TITLE
请问支持hook c code吗？

### ISSUE THREAD

**Issue by bhui** [android-hacker/VirtualXposed#201]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 详细描述
有的app 在so里面有判断xposed的代码 想hook规避下

**Comment by tiann** [comment]
支持，用里面的 inline hook 即可。

**Comment by aaa17106** [comment]
inline hook  怎么用的啊

**Comment by aaa17106** [comment]
有 demo么

**Comment by tiann** [comment]
先了解下inline hook是什么
