### ISSUE TITLE
一加5 7.1.1微信巫师2.72无法打开

### ISSUE THREAD

**Issue by amnextking** [android-hacker/VirtualXposed#23]
手机：一加5
系统版本：氢OS 3.5.0 Android 7.1.1
错误：
无法打开微信巫师界面 但在Xposed中可以找到此模块 
经测试微信巫师部分功能有效 但有些功能需在界面中开启

**Comment by tiann** [comment]
用 2.5.5 版本试下

**Comment by tiann** [comment]
@amnextking 卸载掉2.7.2 重装2.8.0试下；没回复我就认为没问题了。

**Comment by amnextking** [comment]
不好意思才看见 我前两天刷机了 我现在重新装下试试看 稍后给你答复

2018-03-22 1:08 GMT+08:00 weishu <notifications@github.com>:

**Comment by amnextking** [comment]
@tiann @Gh0u1L5 在新环境重新测试了下，新环境较之前复杂的多。
现在手机安装了Magisk 16,又在其中安装了Systemless版的Xposed Framework 89.2.
在不禁用本机Xposed时，我VirtualXposed同时安装好微信和微信巫师，微信巫师无法打开，微信也是无法打开。
![screenshot_20180322-211609](https://user-images.githubusercontent.com/11473678/37774630-b7401056-2e1b-11e8-88fe-af7642747bc6.jpg)

禁用本机Xposed之后，均可打开程序，但微信无法登陆，表现为输入账户密码之后反复闪退到登陆页面。
接着禁用VirtualXposed内的微信巫师，微信可成功登陆，但微信巫师在反复重启VirtualXposed之后有些功能无法使用，重启手机也是如此。
![image](https://user-images.githubusercontent.com/11473678/37774662-cd56c13c-2e1b-11e8-9280-c4fd5ec80ef3.png)

**Comment by tiann** [comment]
稳定性问题另说，打不开的问题先close。
