### ISSUE TITLE
工商app无法启动

### ISSUE THREAD

**Issue by tajoy** [android-hacker/VirtualXposed#248]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

工商app无法启动, 一直显示 "Opening 中国工商银行..."

## 复现步骤

在 VirtualXposed 内安装工行 app, 点击启动.

## 环境

机型： SM-J730G (三星 J7 Pro)
系统版本：7.0
ROM版本：官方原厂 Rom, J730GDXU3ARA2
Xposed 插件以及插件版本：89, 但已禁用
VirtualXposed版本：0.11.2

## 补充

尝试过从真实应用的拷贝app文件到虚拟数据文件位置
cp -rf /data/data/com.icbc/* /data/data/io.va.exposed/virtual/data/user/0/com.icbc/
还是无法启动.
但是相较于直接启动, 多了权限授予的提示框

**Comment by tiann** [comment]
加固APP不支持。
