### ISSUE TITLE
Infinti loading screen :(?

### ISSUE THREAD

**Issue by ayhamo** [android-hacker/VirtualXposed#26]
Hi, sir please as as i installed VirtualXposed and start to install it default application (x posed) it took forever to to pen and wont open, tried lucky patcher with no luck, any help please :(?
S8+ with andoird version of 8.0.0

**Comment by ayhamo** [comment]
i have the latest version of VirtualXposed

**Comment by tiann** [comment]
Sorry to tell you that VirtualXposed is not compatible with Samsung Android Oreo now (Android N is supported).
But i can not find any Samsung Android Oreo device, it may take some time to fix :(

#6

**Comment by ayhamo** [comment]
Ok then i will wait until then, But really i do appreciate your work and hope you can update it  :D

**Comment by tiann** [comment]
Thanks :)

I have received a lot of feedback about Sumsung Android Oreo, I will fix it as soon as possible.

**Comment by ayhamo** [comment]
Then i wish you can notify me as soon as you support it as i can't wait to have it lol :D

**Comment by tiann** [comment]
okay, i will notify you when i solve it at this issue.

**Comment by tiann** [comment]
[VirtualXposed_0.8.6.apk.zip](https://github.com/android-hacker/VirtualXposed/files/1830312/VirtualXposed_0.8.6.apk.zip)

@ayhamo Could you please test this version?

**Comment by ayhamo** [comment]
Hi, i have tried it and worked well, thanks, although i download to try xposed so i don't tried application but did tried lucky patcher and worked so yea loading fixed Ty :)

**Comment by tiann** [comment]
fixed, https://github.com/android-hacker/VirtualXposed/commit/d334cb401b0244621e1fb2ef19d8a02d644153b8
