### ISSUE TITLE
在小米手机的分身中无法正常使用

### ISSUE THREAD

**Issue by Billtec** [android-hacker/VirtualXposed#31]
RT，打开任何一个APP都是停留在 Loading.... ，然后过一会儿就没响应了

**Comment by tiann** [comment]
不支持在系统的分身中用VXP.

**Comment by Billtec** [comment]
是技术上达不到吗？

**Comment by tiann** [comment]
支持这个的目的是什么？没有意义。

**Comment by myvapour** [comment]
这个大部分的人都用不到吧！要作者专门为你开发？

**Comment by tiann** [comment]
什么软件只能在系统的分身中使用？

小米系统分身的实现方式没有研究过，不太清楚。

**Comment by asLody** [comment]
后续会兼容在分身中运行。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Billtec** [comment]
@tiann 我自己有尝试分析了一下，小米分身应该是利用了Android的多用户机制，主空间运行各app的用户是u0_a18这样，分身空间里都是u10_a18这样的。

@asLody VA的大神也出现了，不知道兼容分身做起来容易不，是否有计划？

感谢

**Comment by BrandoZhang** [comment]
> 后续会兼容在分身中运行。
> 
> Sent with [GitHawk](http://githawk.com)

非常期待能在分身中运行！（不好意思挖坟了
