### ISSUE TITLE
Is it possible to introduce built-in privacy control?

### ISSUE THREAD

**Issue by cs-usst** [android-hacker/VirtualXposed#33]
It seems that XPrivacyLua is not supported by VirtualXposed, #7 
Is it possible to add built-in privacy support? [Container](https://github.com/codehz/container) is also an app based on VirtualApp, and it supports model spoofing, so i guess if it's within the VirtualApp, we don't necessarily need to hook system resources to implement privacy control.

**Comment by tiann** [comment]
Yes, it is certainly that we can do this. But i have no time to implement it now.

**Comment by tiann** [comment]
refer : https://github.com/M66B/XPrivacyLua/pull/3

**Comment by tiann** [comment]
fixed: https://github.com/M66B/XPrivacyLua/commit/2f45dba9b2e7c530af845776bdb4b4ec8f05c821
