### ISSUE TITLE
华为荣耀9青春版框架安装后，模板情迁，qq抢红包就闪退

### ISSUE THREAD

**Issue by Iloveyouv** [android-hacker/VirtualXposed#35]
详情，荣耀9  Android8.0  抢红包qq闪退，猜测1，模板与框架不兼容，猜测2，系统版本太高，求解谢谢

**Comment by Iloveyouv** [comment]
下载http://l.xposed.info/repofl
.xml.gz 失败: failed to connect to
dl.xposed.info/45.55.237 (port 80)
from /10.253.76.192 (port 60044) after
30000ms       求解

**Comment by tiann** [comment]
GFW

**Comment by tiann** [comment]
@Iloveyouv 最新版本092还有这个情况吗？

**Comment by qssq** [comment]
我是情迁红包作者，我了shell命令。。复制so命令到被hook的本地库模块，可能这需要改一下源代码，不过最近我发现网上很多人正常使用，我今天也玩一把大神的免root hook工具看看。

**Comment by tiann** [comment]
@qssq 幸会幸会。复制so是用绝对路径吗（/data/data/ 这种）？  如果是的话，可能会有问题

**Comment by qssq** [comment]
的确，我有时间试一下看看错误信息。😉jni问题由于担心不能跨应用访问所以提供了很多兼容读取的方法，比如复制插件apk.得so文件到腾讯qq目录，。用的命令复制的，因为我感觉用java代码写会不会存在权限不够的情况。。
