### ISSUE TITLE
如何用Android Studio编译

### ISSUE THREAD

**Issue by oncealong** [android-hacker/VirtualXposed#36]
请问如何使用Android Studio 编译?
按照wiki, 使用Android Studio打开, 但是报错.
环境:
com.android.tools.build:gradle:3.0.1
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
报错:
```
Error:Could not determine the dependencies of task ':app:compileAospReleaseJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:aospReleaseCompileClasspath'.
   > Could not resolve project :launcher.
     Required by:
         project :app
      > Unable to find a matching configuration of project :launcher: None of the consumable configurations have attributes.
```

然后尝试本地下载Launcher3, 加入VirtualXposed, 报错如下:
```
Error:Unable to resolve dependency for ':app@aospDebug/compileClasspath': Could not resolve project :Launcher3.
<a href="openFile:E:/reverseEngineer/VirtualXposed/VirtualApp/app/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:app@aospDebug/compileClasspath&#39;: Could not resolve project :Launcher3.">Show Details</a>
```

**Comment by tiann** [comment]
launcher 是一个submodule，不用单独clone；直接更新submodule即可。

**Comment by oncealong** [comment]
以前没有使用过git的module模块, 这里补充下:

clone Submodule
==================
1. 下载代码时使用`git clone https://github.com/android-hacker/VirtualXposed.git --recursive`
2. 先clone父项目，再初始化Submodule.
 ```
git clone https://github.com/android-hacker/VirtualXposed.git
cd VirtualXposed\VirtualApp\launcher
git submodule init
git submodule update
```
但是对VirtualXposed, 这两种方法都会报错, 错误是
```
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:android-hacker/Launcher3.git' into submodule path 'E:/reverseEngineer/VX/VirtualXposed/VirtualApp/launcher' failed
Failed to clone 'VirtualApp/launcher'. Retry scheduled
Cloning into 'E:/reverseEngineer/VX/VirtualXposed/VirtualApp/launcher'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.
```
这里的错误原因是因为使用了`git@github.com:android-hacker/Launcher3.git`, 非此项目拥有者没有权限. 我们需要用`https://github.com/android-hacker/Launcher3.git`替代. 找到`.git/config`和`.gitmodules`文件, 修改后即可正常clone代码.


参考资料:
https://segmentfault.com/a/1190000003076028
https://github.com/fastio/pedis/issues/6

**Comment by oncealong** [comment]
导入时报错如下, 请问如何解决? 没有搜到关于`me.weishu.exposed:exposed-core`的资料.
```
Error:Failed to resolve: me.weishu.exposed:exposed-core:0.3.6
<a href="openFile:E:/reverseEngineer/tools/VirtualXposed/VirtualApp/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
```
已根据wiki将exposed-core改为 0.3.6.

**Comment by oncealong** [comment]
将`me.weishu.exposed:exposed-core:0.3.6`改为`me.weishu.exposed:exposed-core:0.+`, 会自动下载0.3.5版本, 所以wiki应该是打错字了. 应该使用`me.weishu.exposed:exposed-core:0.3.5`

**Comment by oncealong** [comment]
make project时又遇到如下错误.
```
Error:(1447, 21) No resource found that matches the given name: attr 'indicatorName'.
Error:(1446, 21) No resource found that matches the given name: attr 'maxHeight'.
Error:(1444, 21) No resource found that matches the given name: attr 'maxWidth'.
Error:(1445, 21) No resource found that matches the given name: attr 'minHeight'.
Error:(1445, 21) No resource found that matches the given name: attr 'minHeight'.
```
![image](https://user-images.githubusercontent.com/5340073/37860160-d8c00b9c-2f5a-11e8-862d-a229f4da07d8.png)

感觉很莫名其妙, 将如下样式注释掉解决, @tiann 请问这个是什么原因导致的.
```
    <!--<style name="AVLoadingIndicatorView">-->
        <!--<item name="minWidth">48dip</item>-->
        <!--<item name="maxWidth">48dip</item>-->
        <!--<item name="minHeight">48dip</item>-->
        <!--<item name="maxHeight">48dip</item>-->
        <!--<item name="indicatorName">BallPulseIndicator</item>-->
    <!--</style>-->
```
![image](https://user-images.githubusercontent.com/5340073/37860180-2bf19560-2f5b-11e8-956b-b91076e6187d.png)

**Comment by oncealong** [comment]
接下来make project又遇到错误, 这次更不可思议, 是`Epic.collectOffsetInfo()`报错, 显示`Epic`没有`collectOffsetInfo()`这个方法. 
![image](https://user-images.githubusercontent.com/5340073/37860208-7a032ed0-2f5b-11e8-993e-01814987baa8.png)
不知道是哪个组件使用的`me.weishu:epic:0.3.3`, 我去看了最新版的Epic https://github.com/tiann/epic/blob/master/library/src/main/java/me/weishu/epic/art/Epic.java, 确实没有找到这个方法.
![image](https://user-images.githubusercontent.com/5340073/37860213-997929ea-2f5b-11e8-9986-bf80ee0dea81.png)

@tiann 请问这个是由于什么导致的?

**Comment by ygd2013520** [comment]
用AS打开，最后出现如下错误，无法解决
![2018-08-15 3 58 37](https://user-images.githubusercontent.com/15338272/44137759-25379e26-a0a4-11e8-8ac3-bf8773edc1a5.png)
