### ISSUE TITLE
没有适配18:9屏幕

### ISSUE THREAD

**Issue by shan999abc** [android-hacker/VirtualXposed#37]
小米MIX2全面屏手机，屏幕下方露出桌面了。没有适配18:9屏幕 。

**Comment by tiann** [comment]
没有手机，暂无法适配。

**Comment by tiann** [comment]
首页，最下面没有一个按钮吗？
或者虚拟按键里没有出现菜单？
再或者长按最近任务/菜单键没有？

如果以上方法都不行，可以长按主屏幕任意空白处。

**Comment by davidwudv** [comment]
长按主屏幕任意空白处可以了，谢谢！
我咋没找到这个使用说明。
我是按照

>在VirtualXposed中安装App有两种方式：
> 1. 直接复制已经在系统中安装好的APP，比如如果你系统中装了微信，那么可以直接复制一份。
> 2. 通过外置存储直接安装APK文件；点主界面的➕，然后选择后面两个TAB即可。

这个说明，找了半天没找到主界面的➕。。。。。。。=.=

**Comment by tiann** [comment]
@davidwudv 界面改版了，文档木有更新。

**Comment by Insenc** [comment]
这个是系统问题，解决方式是在设置-全面屏-应用全屏运行设置里面允许应用全屏运行。

**Comment by tiann** [comment]
fixed: https://github.com/android-hacker/VirtualXposed/commit/5e74003ce7a7d87a37279d9e35f26a4a5a38b8be
