### ISSUE TITLE
请问此应用多久rebase一次VirtualApp的最新commit？

### ISSUE THREAD

**Issue by tenwx** [android-hacker/VirtualXposed#41]
RT，看VirtualApp到changlog貌似已经解决了app依赖google play无法运行的问题

**Comment by tiann** [comment]
VirtualApp 开源版已经停止维护了。作为一个独立的分支，VirtualXposed会向前发展；但是只会解决与VirtualXposed相关的问题。

**Comment by tenwx** [comment]
我看到VirtualApp的最新一次提交是3月13日，changlog：
1、修复某些rom下，快捷方式图标不正确
2、兼容以前组件StubFileProvider
3、适配部分新ROM的虚拟IMEI

**Comment by tiann** [comment]
只改了readme，没有代码。
