### ISSUE TITLE
在VirtualXposed内微信点开钱包闪退问题

### ISSUE THREAD

**Issue by batumgl** [android-hacker/VirtualXposed#44]
一加5手机
H2OS-5.0.2 
安卓版本-8.0.0 
微信版本-6.6.5 
VirtualXposed版本-0.8.6

一开始直接安装了微信及微X模块，点开微信钱包界面就会闪退，然后卸载了微X模块，并彻底杀进程且重启VirtualXposed后，点开微信钱包依然闪退，VirtualXposed内卸载微信并重装，登录后点开钱包依然闪退，不知道是一加5不兼容，还是VirtualXposed为了安全起见不允许访问微信钱包呀

**Comment by tiann** [comment]
是否装了别的插件？

**Comment by batumgl** [comment]
前几天课比较多没有及时回复，抱歉！
没有安装除了微X模块外的任何插件，之前微X模块版本为1.20
刚更新了VirtualXposed版本0.8.7，卸载微X模块插件只保留微信，依然会出现点开微信钱包界面闪退的现象，卸载微信并重装，现象依旧
另外之前没有阐述清楚，除了(1)点开微信钱包界面闪退以外，(2)点击微信右上角+号收付款也会闪退，微信扫一扫功能扫普通二维码正常，(3)但扫收款码会闪退，聊天界面发送红包一切正常，收红包也正常，(4)但点转账就会闪退，而转账收款一切正常
也即目前使用过程中，除了收/发红包及转账收款以外，其余涉及钱的操作(以上4点)均会触发闪退，我对安卓开发不是很熟悉，烦请您百忙中抽时间做一下适配，感谢！

**Comment by Outofeelings** [comment]
我的微信也出现了相同情况。VXP是0.8.5，微信6.6.5。在xp上把插件去钩后也有出现。在VXP中尝试修复，也无果。手机是坚果pro2，安卓7.1.1。暂未发现能正常使用的时候～

**Comment by Outofeelings** [comment]
搞定了，不要装最新的6.6.5微信就没问题了。

**Comment by batumgl** [comment]
还是不行 换了微信6.6.3没有装任何插件 前述4个操作依然会出现闪退的情况

**Comment by Outofeelings** [comment]
我0.8.5+6.6.3或0.8.5+6.5.10都正常使用

**Comment by batumgl** [comment]
还是会闪退QAQ
