### ISSUE TITLE
XiaoMi 6 微信巫师加载失败

### ISSUE THREAD

**Issue by luv135** [android-hacker/VirtualXposed#45]
![_20180327172441](https://user-images.githubusercontent.com/8563420/37958765-ed588620-31e3-11e8-9378-1b070032576b.jpg)

**Comment by tiann** [comment]
系统，ROM，VXP，微信巫师版本多少？

**Comment by luv135** [comment]
MIUI 9.8.3.22 开发版 Android 8.0.0
Xposed 3.1.5
VXP 0.8.5
微信巫师 2.7.1

**Comment by tiann** [comment]
微信巫师 2.8.0  或者 2.5.5 试一下。

**Comment by luv135** [comment]
微信巫师 2.8.0  可以跑起来
