### ISSUE TITLE
华为P10 PLUS（EMUI 8.0系统）无法使用

### ISSUE THREAD

**Issue by mao13820** [android-hacker/VirtualXposed#49]
不好意思打扰您了，我在使用过程中遇到一些问题想向您询问，希望您能帮忙看看，谢谢您了！
以下是问题描述。
1.我想在virtualxposed里面使用网易云音乐和音量增强器。
2.使用的网易云音乐版本是4.3.0，音乐增强器是0.0.25，virtualxposed是最新的0.8.5版本。
3.经过测试在小米5上是可以使用的，网易云音乐和音量增强器配合的很好。这说明使用步骤上应该没有问题。
4.但是在系统为EMUI8.0的P10 PLUS上无法使用，表现为，安装和运行都正常，没有报错，但是在激活所有部件后，打开网易云音乐，提示无版权，这说明音量增强器没有起作用，因为只要该xposed插件起作用了，即使插件错误，也不会显示无版权。无版权提示是网易云音乐自带的提示。
5.以下是xposed框架中的日志

--------- beginning of system
--------- beginning of main
03-31 17:27:10.395 I/DexposedBridge(14273): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
03-31 17:27:10.395 I/DexposedBridge(14273): Loading modules from /data/user/0/io.va.exposed/virtual/data/app/bin.xposed.Unblock163MusicClient/base.apk
03-31 17:27:10.407 I/DexposedBridge(14273):   Loading class bin.xposed.Unblock163MusicClient.Main
03-31 17:27:10.416 I/DexposedBridge(14273): module:/data/user/0/io.va.exposed/virtual/data/app/com.netease.cloudmusic/base.apk is disabled, ignore
03-31 17:27:11.343 I/DexposedBridge(14433): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
03-31 17:27:11.344 I/DexposedBridge(14433): Loading modules from /data/user/0/io.va.exposed/virtual/data/app/bin.xposed.Unblock163MusicClient/base.apk
03-31 17:27:11.377 I/DexposedBridge(14433):   Loading class bin.xposed.Unblock163MusicClient.Main
03-31 17:27:11.394 I/DexposedBridge(14433): module:/data/user/0/io.va.exposed/virtual/data/app/com.netease.cloudmusic/base.apk is disabled, ignore
03-31 17:27:36.914 I/DexposedBridge(14713): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
03-31 17:27:36.914 I/DexposedBridge(14713): Loading modules from /data/user/0/io.va.exposed/virtual/data/app/bin.xposed.Unblock163MusicClient/base.apk
03-31 17:27:36.926 I/DexposedBridge(14713):   Loading class bin.xposed.Unblock163MusicClient.Main
03-31 17:27:36.931 I/DexposedBridge(14713): module:/data/user/0/io.va.exposed/virtual/data/app/com.netease.cloudmusic/base.apk is disabled, ignore
03-31 17:27:45.313 I/DexposedBridge(14782): xposed config file exists, check version
03-31 17:27:45.314 I/DexposedBridge(14782): xposed version keep same, continue.
03-31 17:27:45.330 I/XposedInstaller(14782): null getActivityXposedVersion called.
03-31 17:27:45.340 I/DexposedBridge(14782): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
03-31 17:27:45.340 I/DexposedBridge(14782): Loading modules from /data/user/0/io.va.exposed/virtual/data/app/bin.xposed.Unblock163MusicClient/base.apk
03-31 17:27:45.353 I/DexposedBridge(14782):   Loading class bin.xposed.Unblock163MusicClient.Main
03-31 17:27:45.356 I/DexposedBridge(14782): module:/data/user/0/io.va.exposed/virtual/data/app/com.netease.cloudmusic/base.apk is disabled, ignore
03-31 17:27:56.607 I/DexposedBridge(14782): module fragment reload success, activity:de.robv.android.xposed.installer.WelcomeActivity@a86e88f

最后，再次谢谢您，不好意思麻烦您了，希望您能够帮忙看看。

**Comment by loveinangeR** [comment]
Sorry我不是开发者。我也没有华为手机。我也不使用那个模块。我直接使用XPOsed的。帮不到您了。

发送自我的Sony Xperia™智能手机


---- mao13820编写 ----


不好意思打扰您了，我在使用过程中遇到一些问题想向您询问，希望您能帮忙看看，谢谢您了！
以下是问题描述。
1.我想在virtualxposed里面使用网易云音乐和音量增强器。
2.使用的网易云音乐版本是4.3.0，音乐增强器是0.0.25，virtualxposed是最新的0.8.5版本。
3.经过测试在小米5上是可以使用的，网易云音乐和音量增强器配合的很好。这说明使用步骤上应该没有问题。
4.但是在系统为EMUI8.0的P10 PLUS上无法使用，表现为，安装和运行都正常，没有报错，但是在激活所有部件后，打开网易云音乐，提示无版权，这说明音量增强器没有起作用，因为只要该xposed插件起作用了，即使插件错误，也不会显示无版权。无版权提示是网易云音乐自带的提示。
5.以下是xposed框架中的日志

--------- beginning of system
--------- beginning of main
03-31 17:27:10.395 I/DexposedBridge(14273): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
03-31 17:27:10.395 I/DexposedBridge(14273): Loading modules from /data/user/0/io.va.exposed/virtual/data/app/bin.xposed.Unblock163MusicClient/base.apk
03-31 17:27:10.407 I/DexposedBridge(14273): Loading class bin.xposed.Unblock163MusicClient.Main
03-31 17:27:10.416 I/DexposedBridge(14273): module:/data/user/0/io.va.exposed/virtual/data/app/com.netease.cloudmusic/base.apk is disabled, ignore
03-31 17:27:11.343 I/DexposedBridge(14433): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
03-31 17:27:11.344 I/DexposedBridge(14433): Loading modules from /data/user/0/io.va.exposed/virtual/data/app/bin.xposed.Unblock163MusicClient/base.apk
03-31 17:27:11.377 I/DexposedBridge(14433): Loading class bin.xposed.Unblock163MusicClient.Main
03-31 17:27:11.394 I/DexposedBridge(14433): module:/data/user/0/io.va.exposed/virtual/data/app/com.netease.cloudmusic/base.apk is disabled, ignore
03-31 17:27:36.914 I/DexposedBridge(14713): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
03-31 17:27:36.914 I/DexposedBridge(14713): Loading modules from /data/user/0/io.va.exposed/virtual/data/app/bin.xposed.Unblock163MusicClient/base.apk
03-31 17:27:36.926 I/DexposedBridge(14713): Loading class bin.xposed.Unblock163MusicClient.Main
03-31 17:27:36.931 I/DexposedBridge(14713): module:/data/user/0/io.va.exposed/virtual/data/app/com.netease.cloudmusic/base.apk is disabled, ignore
03-31 17:27:45.313 I/DexposedBridge(14782): xposed config file exists, check version
03-31 17:27:45.314 I/DexposedBridge(14782): xposed version keep same, continue.
03-31 17:27:45.330 I/XposedInstaller(14782): null getActivityXposedVersion called.
03-31 17:27:45.340 I/DexposedBridge(14782): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
03-31 17:27:45.340 I/DexposedBridge(14782): Loading modules from /data/user/0/io.va.exposed/virtual/data/app/bin.xposed.Unblock163MusicClient/base.apk
03-31 17:27:45.353 I/DexposedBridge(14782): Loading class bin.xposed.Unblock163MusicClient.Main
03-31 17:27:45.356 I/DexposedBridge(14782): module:/data/user/0/io.va.exposed/virtual/data/app/com.netease.cloudmusic/base.apk is disabled, ignore
03-31 17:27:56.607 I/DexposedBridge(14782): module fragment reload success, activity:de.robv.android.xposed.installer.WelcomeActivity@a86e88f

最后，再次谢谢您，不好意思麻烦您了，希望您能够帮忙看看。

**Comment by tiann** [comment]
duplicate #67 疑似 8.0 系统的问题，我单独看下。
