### ISSUE TITLE
退出virtualxposed需要按两次返回键,第一次会闪一下

### ISSUE THREAD

**Issue by gedoor** [android-hacker/VirtualXposed#5]
退出virtualxposed需要按两次返回键,第一次会闪一下

**Comment by tiann** [comment]
没有复现此场景，能提供更详细的信息吗？

**Comment by gedoor** [comment]
这是录制的视频,另外还有个bug,安装这个软件会出现两个图标,其它软件正常

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: weishu <notifications@github.com>
发送时间: Monday, March 12, 2018 10:51:32 AM
收件人: android-hacker/VirtualXposed
抄送: kunfei; Author
主题: Re: [android-hacker/VirtualXposed] 退出virtualxposed需要按两次返回键,第一次会闪一下 (#5)


没有复现此场景，能提供更详细的信息吗？

―

**Comment by gedoor** [comment]
这会儿试了下没有这种情况了
