### ISSUE TITLE
微信无法提示消息

### ISSUE THREAD

**Issue by Jerrychenshen** [android-hacker/VirtualXposed#50]
三星S8+ 8.0系统
只要软件一后台，XVP里的微信没接受消息，只有重新打开软件才能接收。

**Comment by firesunCN** [comment]
三星的智能管理器把VXP设置为允许自启 同时不要屏蔽VXP的通知

**Comment by Jerrychenshen** [comment]
我测试了一下是微信巫师的问题，挂载了微信巫师就微信就经常重启，崩溃，收不到消息。换成微x助手，微信异常缓慢，是不是黑屏，并且没有该有的功能。


火日攻天@firesun <notifications@github.com> 于 2018年4月2日周一 上午5:40写道：

**Comment by jjjyyyllll** [comment]
S9+  安卓8。  微信不能运行巫师、微X，打开就闪退。关闭插件，微信就正常 @tiann 。大神求解决。

**Comment by firesunCN** [comment]
我是s9+ 发现运行巫师要这样 先在VXP重启，然后开巫师，然后在开微信，这样正常
不过我遇到一个问题是在0.87里开巫师，巫师的界面提示xposed版本过低，我全部卸掉装0.86，然后重装微信，巫师就可以了

**Comment by Jerrychenshen** [comment]
感谢，按照你说的能用了，必须先开巫师，再开微信才可以。但是0.86版本三星管理器一直报毒，真是尴尬啊，有一点真的很奇怪，装了0.87版本提示xposed版本过低。。。。

火日攻天@firesun <notifications@github.com> 于 2018年4月2日周一 下午2:53写道：

**Comment by tiann** [comment]
@Jerrychenshen 报毒的问题，用0.8.7试下

**Comment by Jerrychenshen** [comment]
0.87微信巫师不能用啊，提示xposed版本过低，我是没办法才用0.86的。

weishu <notifications@github.com> 于 2018年4月3日周二 上午1:27写道：

**Comment by tiann** [comment]
@Jerrychenshen @firesunCN 谢谢反馈。0.8.7的问题已经修复了，可以用 [VirtualXposed_0.8.8.apk](https://github.com/android-hacker/VirtualXposed/releases/tag/0.8.8)试一下。

**Comment by firesunCN** [comment]
@tiann 0.8.8解决了

**Comment by firesunCN** [comment]
@Jerrychenshen 我现在没用巫师了，在用自己写的插件

**Comment by zhang214214** [comment]
@firesunCN 你们hook的方法都是逆向找到的吗？

**Comment by tiann** [comment]
@zhang214214 必然的，难道微信会自己告诉你？

**Comment by tiann** [comment]
092已修复
