### ISSUE TITLE
貌似会和真机上的xposed冲突

### ISSUE THREAD

**Issue by hetykai** [android-hacker/VirtualXposed#51]
是这样的，我手机(Los14.1)本身已经刷了xposed，我是用这个来开发插件的。手机装了要hook的目标应用和xp插件，vxp内也装了目标应用和xp插件。结果是真机上不启用xp插件的情况下，在vxp内运行插件和目标应用良好。但是一旦在真机xp上启用了xp插件，vxp内的目标应用启动加载时就会崩溃。

**Comment by tiann** [comment]
真机上启用了，就不要在里面装了，里面自动生效的。

**Comment by tiann** [comment]
机制如此 won't fix.
