### ISSUE TITLE
Can't open Mobike within VirtualXposed

### ISSUE THREAD

**Issue by JohnChu101** [android-hacker/VirtualXposed#55]
error message: open Mobike failed

**Comment by tiann** [comment]
what is your os version, rom version and mobike version?

**Comment by JohnChu101** [comment]
@tiann Samsung TouchWiz based on Android 7.0. 
Mobike: 7.0.1

**Comment by JohnChu101** [comment]
I tried the latest version of Mobike as well (7.1.0) and it doesn't help.

**Comment by tiann** [comment]
I have tried it on my Xiaomi Note3, it works well. Did you install any Xposed Modules? please try disable all the plugins and open it again.

**Comment by JohnChu101** [comment]
I don't have any module installed in VirtualXposed.

**Comment by tiann** [comment]
ok, i will test it on samsung.
