### ISSUE TITLE
有办法让里面的app不要相互唤醒吗？

### ISSUE THREAD

**Issue by yorks** [android-hacker/VirtualXposed#58]
比如我打开 链家app 然后会自动唤醒里面的 淘宝，smzdm，企业wx。。。，需要手工进去 `任务管理` 里面一个一个杀掉。。。

我试过用 xpose 的模块 `阻止运行`， `绿色运行` 都卡在第一界面，获取数据....

**Comment by tiann** [comment]
暂时没有办法，需要单独开发。但是VirtualXposed的主要目标不是这个。

**Comment by glovebx** [comment]
阻止链式唤醒有apk的，yorks可以上酷安等地找一下

**Comment by yorks** [comment]
@glovebx 我觉得你理解错了，我说的是在 VirtualXposed 里面的app 阻止相互唤醒，而不是本身手机系统里面的。

**Comment by scskarsper** [comment]
我也在想这个。如果能把冰箱（icebox之类）的功能集成进去就好了。顺便：增加创建快捷方式的功能把不在虚拟机里的app链到桌面上，然后就可以直接当安卓桌面用了
