### ISSUE TITLE
三星S9+安装后，所有添加程序都打不开，一直在opening，连xposed也是如此

### ISSUE THREAD

**Issue by jjjyyyllll** [android-hacker/VirtualXposed#6]
三星S9+安装后，所有的程序都打不开，一直在opening，连xposed也是如此

**Comment by jjjyyyllll** [comment]
@tiann 求大神解决~~ Android 8.0

**Comment by tiann** [comment]
一直问题，但目前找不到8.0的三星手机；再等等吧

**Comment by tiann** [comment]
fixed, https://github.com/android-hacker/VirtualXposed/commit/d334cb401b0244621e1fb2ef19d8a02d644153b8
