### ISSUE TITLE
三星S9无法开启微信自带的指纹支付

### ISSUE THREAD

**Issue by kk99bb** [android-hacker/VirtualXposed#61]
机型：三星S9 港版（已刷国行）
系统：安卓8.0 真机未root 未装XP框架

问题1：可以进入微信，微X模块可以使用。但微信用几分钟就会崩溃闪退，即使只装微信，不装模块问题也依旧。测试了多个版本的微信、VirtualXposed都存在这个问题。

问题2：微信无法开启指纹支付（会弹出一段英文提示），微信小程序能打开但不能用，测试了OFO、摩拜单车，进入小程序后一直是加载的状态。

**Comment by tiann** [comment]
谢谢提供如此有用的信息，马上手机到货了，我再看看。

**Comment by jjjyyyllll** [comment]
@tiann 已经更新到0.8.9还是不行，打开微X、巫师、MDWechat还是会闪，微信增强倒是正常。

而且已经把vae和vae里面微信设置不杀掉后台，过一段时间vae里面的微信在后台还是收不到实时信息，需要打开。

**Comment by tiann** [comment]
闪退的问题装一下新版本 0.12.1 应该会好一些。
指纹支付的问题，由于我没有对应的设备，暂时无法修复；可以使用“指纹支付”这个Xposed插件代替。
