### ISSUE TITLE
小米平板4在VirtualXposed上安装新版本的kindle闪退

### ISSUE THREAD

**Issue by nmaccount** [android-hacker/VirtualXposed#625]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

小米平板4在VirtualXposed上安装新版本的kindle闪退

## 复现步骤

在VirtualXposed上安装新版本（kindle7.2.0.29之后的版本）的kindle出现闪退闪退

## 环境

机型：小米平板4
系统版本：8.1.0;
ROM版本：MIUI9.6.3.0;
Xposed 插件以及插件版本：Xinternal SD-4.8
VirtualXposed版本：0.17.3

## 补充

在1台三星Android6.0的设备上，能够安装新版的kindle，但是在小米平板4上不行，不知道是不是小米系统的问题

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
不支持平板
