### ISSUE TITLE
VirtualXposed内打开新安装应用，提示VirtualXposed已停止运行

### ISSUE THREAD

**Issue by qiaop** [android-hacker/VirtualXposed#63]
VirtualXposed版本：VirtualXposed_0.8.9.apk
微信版本：6.6.6
钉钉版本：4.3.3
设备信息：
设备名称：OnePlus 5
型号：ONEPLUS A5000
系统版本：Android 8.0.0
未root

**Comment by tiann** [comment]
新版（099）已解决
