### ISSUE TITLE
Android 8.0 音樂增強器無法使用

### ISSUE THREAD

**Issue by k1122964** [android-hacker/VirtualXposed#67]
HTC U Ultra 8.0使用0.92版本的virtualxposed搭配音樂增強無效，安裝過很多版本的網易雲了，功能都無法使用。

**Comment by tiann** [comment]
已修复：https://github.com/android-hacker/exposed/commit/5258cda1d3298b91de91d2f31cbd2cdf222771db

请使用 0.9.4 版本。
