### ISSUE TITLE
酷安读取不了应用

### ISSUE THREAD

**Issue by jaytyfxb** [android-hacker/VirtualXposed#68]
里面可以增加个权限管理就好了，app settings好像不能用

**Comment by jaytyfxb** [comment]
而且酷安里发不了图片

**Comment by tiann** [comment]
酷安是因为他要判断有5个以上的系统应用才行；但是VXP内部屏蔽了对系统应用的查看。所以不会修复。
权限管理就算加了 app settings也用不了。
