### ISSUE TITLE
Xposed模块打不开

### ISSUE THREAD

**Issue by phone-burner** [android-hacker/VirtualXposed#708]
**反馈BUG之前，先issue里面搜看看有没有别我QQ净化已经反馈过，重复的不予处理！！**

## 问题描述：我在VXP里安装了QQ,AD快消，QQ净化，后两个模块在Xposed Installer里正常激活使用。不知在什么时候，Xposed Installer突然打不开了（系统提示异常退出），但模块和应用能正常使用。现在，我能够正常安装/卸载应用，但是模块不能启用/停用。

（请尽量详细地描述你遇到的问题）

## 环境

机型：MI 6X
系统版本：Android 9 
ROM版本：MIUI10 9.8.22开发版
Xposed 插件以及插件版本：不知道（打不开），是常用模块提供的最新版
VirtualXposed版本：0.17.3

## 补充
系统log:*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/wayne/wayne:9/PKQ1.180904.001/9.8.22:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 20713, tid: 20713, name: posed.installer  >>> de.robv.android.xposed.installer <<<
signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xe9e7d209
    r0  7ce15320  r1  cfffffff  r2  ed6378a8  r3  ed498bd3
    r4  7ce15320  r5  00000000  r6  00000000  r7  e9e7d001
    r8  00000000  r9  f13ce000  r10 00000000  r11 ffbe021c
    ip  e9bb7468  sp  ffbe0210  lr  ed5cf577  pc  e9e7d0c8

backtrace:
    #00 pc 000000c8  <anonymous:e9e7d000>
    #01 pc 0040e575  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
    #02 pc 003e808b  /system/lib/libart.so (art_quick_invoke_static_stub+222)
    #03 pc 000a1427  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+154)
    #04 pc 000e582d  /system/lib/libart.so (art::ClassLinker::InitializeClass(art::Thread*, art::Handle<art::mirror::Class>, bool, bool)+1528)
    #05 pc 000d5817  /system/lib/libart.so (art::ClassLinker::EnsureInitialized(art::Thread*, art::Handle<art::mirror::Class>, bool, bool)+130)
    #06 pc 001e487f  /system/lib/libart.so (art::ResolveVerifyAndClinit(art::dex::TypeIndex, art::ArtMethod*, art::Thread*, bool, bool)+198)
    #07 pc 003cef13  /system/lib/libart.so (artInitializeStaticStorageFromCode+46)
    #08 pc 0040e9cf  /system/lib/libart.so (art_quick_initialize_static_storage+30)
    #09 pc 00208fb9  /data/app/io.va.exposed-EKs9KejiymNheokp3gbPDw==/oat/arm/base.odex (offset 0xe2000) (me.weishu.exposed.ExposedBridge.loadModule+3784)
    #10 pc 00297a5d  /data/app/io.va.exposed-EKs9KejiymNheokp3gbPDw==/oat/arm/base.odex (offset 0xe2000) (com.lody.virtual.client.VClientImpl.bindApplicationNoCheck+4780)
    #11 pc 0029be41  /data/app/io.va.exposed-EKs9KejiymNheokp3gbPDw==/oat/arm/base.odex (offset 0xe2000) (com.lody.virtual.client.VClientImpl.bindApplication+128)
    #12 pc 0029bfc7  /data/app/io.va.exposed-EKs9KejiymNheokp3gbPDw==/oat/arm/base.odex (offset 0xe2000) (com.lody.virtual.client.VClientImpl.bindApplicationForActivity+86)
    #13 pc 0040e575  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
    #14 pc 003e7f89  /system/lib/libart.so (art_quick_invoke_stub+224)
    #15 pc 000a1415  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+136)
    #16 pc 001e6615  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+236)
    #17 pc 001e1881  /system/lib/libart.so (bool art::interpreter::DoCall<false, true>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1488)
    #18 pc 001f72f5  /system/lib/libart.so (_ZN3art11interpreterL8DoInvokeILNS_10InvokeTypeE2ELb0ELb1EEEbPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+580)
    #19 pc 001f5437  /system/lib/libart.so (void art::interpreter::ExecuteSwitchImplCpp<true, false>(art::interpreter::SwitchImplContext*)+50894)
    #20 pc 00413455  /system/lib/libart.so (offset 0x407000) (ExecuteSwitchImplAsm+4)
    #21 pc 00191a6c  /data/app/io.va.exposed-EKs9KejiymNheokp3gbPDw==/oat/arm/base.vdex (android.app.TransactionHandlerProxy.handleLaunchActivity)
    #22 pc 001c584f  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.4289152980+318)
    #23 pc 001c9eb7  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+82)
    #24 pc 003d66e9  /system/lib/libart.so (artQuickToInterpreterBridge+880)
    #25 pc 00412aff  /system/lib/libart.so (offset 0x406000) (art_quick_to_interpreter_bridge+30)
    #26 pc 0135ff1b  /system/framework/arm/boot-framework.oat (offset 0x9e8000) (android.app.servertransaction.LaunchActivityItem.execute+410)
    #27 pc 00a91bfd  /system/framework/arm/boot-framework.oat (offset 0x9e8000) (android.app.servertransaction.TransactionExecutor.executeCallbacks+516)
    #28 pc 00a919a1  /system/framework/arm/boot-framework.oat (offset 0x9e8000) (android.app.servertransaction.TransactionExecutor.execute+216)
    #29 pc 00dc096f  /system/framework/arm/boot-framework.oat (offset 0x9e8000) (android.app.ActivityThread$H.handleMessage+478)
    #30 pc 01467bc9  /system/framework/arm/boot-framework.oat (offset 0x9e8000) (android.os.Handler.dispatchMessage+136)
    #31 pc 01ad62bd  /system/framework/arm/boot-framework.oat (offset 0x9e8000) (android.os.Looper.loop+1172)
    #32 pc 00dd1513  /system/framework/arm/boot-framework.oat (offset 0x9e8000) (android.app.ActivityThread.main+674)
    #33 pc 0040e575  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
    #34 pc 003e808b  /system/lib/libart.so (art_quick_invoke_static_stub+222)
    #35 pc 000a1427  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+154)
    #36 pc 003487fd  /system/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)
    #37 pc 00349c4d  /system/lib/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+1024)
    #38 pc 002fbc21  /system/lib/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+40)
    #39 pc 006abee7  /system/framework/arm/boot-core-oj.oat (offset 0x4a3000) (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+110)
    #40 pc 01edeb9b  /system/framework/arm/boot-framework.oat (offset 0x9e8000) (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+114)
    #41 pc 01ef3569  /system/framework/arm/boot-framework.oat (offset 0x9e8000) (com.android.internal.os.ZygoteInit.main+1824)
    #42 pc 0040e575  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
    #43 pc 003e808b  /system/lib/libart.so (art_quick_invoke_static_stub+222)
    #44 pc 000a1427  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+154)
    #45 pc 003487fd  /system/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)
    #46 pc 00348627  /system/lib/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+310)
    #47 pc 0028f69d  /system/lib/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+444)
    #48 pc 0006ec25  /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+28)
    #49 pc 00070ea9  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+520)
    #50 pc 00001b1f  /system/bin/app_process32 (main+886)
    #51 pc 000a1a79  /system/lib/libc.so (offset 0x62000) (__libc_init+48)
    #52 pc 00001767  /system/bin/app_process32 (_start_main+38)
    #53 pc 000000c4  <unknown>

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/releases/tag/0.18.0
