### ISSUE TITLE
三星S9+ 支付宝无法打开朋友消息

### ISSUE THREAD

**Issue by lzb16** [android-hacker/VirtualXposed#71]
机型：三星S9+
系统：Android8.0 未root
VirtualXposed版本：0.9.4
支付宝版本：10.1.20.568

问题：在VirtualXposed中打开支付宝，切换到“朋友”tab页， 朋友发的消息无法打开，但公众号的消息可以打开

**Comment by tiann** [comment]
unimportant, won't fix.
