### ISSUE TITLE
网易云音乐5.1的外置SD卡读取问题。

### ISSUE THREAD

**Issue by aqcnbbs** [android-hacker/VirtualXposed#75]
RT，在网易云音乐的设置里，
“设置下载目录 ” 这个选项没有外置SD的选择。

**Comment by tiann** [comment]
不在VirtualXposed中安装，是否有这个问题？

**Comment by aqcnbbs** [comment]
不在vx中使用网易云音乐是可以正常把下载目录设置到外置sd卡的。

**Comment by lxztktz** [comment]
大神，VirtualXposed作为系统桌面的话，可以把应用数据放置在外置SD卡中么？
希望加入这个功能，或者存储重定向时可以设置成外置SD卡，国内APP数据量太大了😭

**Comment by tiann** [comment]
不可以，VirtualXposed 的核心功能是使用 Xposed。其他的无关需求，没那个时间和精力维护。
