### ISSUE TITLE
更新后网易云启动卡界面

### ISSUE THREAD

**Issue by AlliotTech** [android-hacker/VirtualXposed#78]
版本  0.9.7版  
打开网易云，每次动画切换必须将VXposeed弹回桌面再进入，才能正常。

**Comment by tiann** [comment]
机型，系统版本？

**Comment by AlliotTech** [comment]
vivo 安卓7.1.2  
开了网易云音乐增强   (今天更新的框架，没更新前正常)

**Comment by tiann** [comment]
更新前是什么版本？

**Comment by aqcnbbs** [comment]
我之前用网易云音乐5.1之前的版本也是会，更新到5.1和vx0.9.8就可以了。
手机是三星s7 安卓7.0

**Comment by AlliotTech** [comment]
更新前的版本不记得了，应该是上一个版本。  网易云5.1的版本已经试过了。。。依旧卡屏。。

**Comment by tiann** [comment]
用低版本的网易云音乐（比如4.3.2）试试。

**Comment by flyher** [comment]
@tiann 
一加，Android8，0.9.7版，网易云音乐5.0版本，同样的问题。
--------
另外，阿里系常见应用装上去都是闪退，

**Comment by flyher** [comment]
@tiann
没有装。
另外升级到了安卓8.1，发现vx里面装的软件会被清空😂，之前正常运行的部分软件同样出现了闪退，例如“手机百度”，

**Comment by tiann** [comment]
系统升级之后软件会被清空，已知问题。

**Comment by tiann** [comment]
“每次动画切换必须将VXposeed弹回桌面再进入” 跟  @ttorange1 说的 “之前是插件无效，之后是卡在正在启动的界面上（临时禁用插件则可以正常打开）。” 貌似不是一个情况？

意思是最后可以打开？

**Comment by ttorange1** [comment]
@tiann 准确的说，应该是：
之前低版本是插件勾选了也无效，之后（大概0.97及之后)是卡在正在启动的界面上进不去（临时禁用插件则可以正常打开）。

**Comment by Moniga** [comment]
刚刚试着把音量增强模块关了进网易云，发现使用并没有任何问题，所以这应该是音量增强的锅……

**Comment by AlliotTech** [comment]
并不是。。。  删除vxp框架 清理残余   重新安装网易云与音量增强 以及 vxp 解决了。。

**Comment by tiann** [comment]
fixed: https://github.com/android-hacker/exposed/commit/dfcf21cccaefc35f83be17eb91f3872d68427701

reason: 重复加载模块。
