### ISSUE TITLE
APP内无法直接更新QQ

### ISSUE THREAD

**Issue by loveless6trq** [android-hacker/VirtualXposed#79]
版本0.9.7
APP外添加新版本无法使用升级安装，选择升级安装后一直显示升级中，只能选择安装分身，但是分身安装的也是旧版本
直接在APP内打开QQ后下载新版本后安装升级，屏幕闪了一下就没有任何反应了……
想要删除分身APP就会停止运行然后闪退

**Comment by tiann** [comment]
请耐心等待。

**Comment by loveless6trq** [comment]
等了一个小时还是显示正在安装也是正常的吗……

**Comment by loveless6trq** [comment]
卸载了重装还是没办法在APP内直接升级安装……聊天记录也没有了……

**Comment by tiann** [comment]
应该是你更新的QQ没有签名引起的，VXP内不支持安装没有签名的应用。
