### ISSUE TITLE
Add GameGuardian support apk to new releases

### ISSUE THREAD

**Issue by Enyby** [android-hacker/VirtualXposed#80]
If possible, make a second apk for each new release that would be compatible with GameGuardian.

Thank you.

Adding the debuggable flag via apktool for some users breaks the application. Perhaps because of the fact that we need to re-sign with a test signature.

**Comment by tiann** [comment]
@Enyby I have make a new release for GameGuardian: https://github.com/android-hacker/VirtualXposed/releases/tag/0.9.8

(Download the VirtualXposed_0.9.8_for_GameGuardian.apk)

And also, I will make two apks in every new release in future :) 

Thanks for your advice.

**Comment by Enyby** [comment]
@tiann https://github.com/android-hacker/VirtualXposed/releases/tag/0.11.1 Only one APK.

**Comment by tiann** [comment]
sorry, It is too late yesterday, i will add It soon

**Comment by Enyby** [comment]
@tiann https://github.com/android-hacker/VirtualXposed/releases/tag/0.12.9 Only one APK.

**Comment by tiann** [comment]
@Enyby It is just for test on Android 9.0, use 0.12.7 if you are not android 9.0; And there are many bugs in 0.12.9 on Android 9.0, it is not recommended to use.

**Comment by tiann** [comment]
Please use [0.13.0](https://github.com/android-hacker/VirtualXposed/releases/tag/0.13.0)

**Comment by Enyby** [comment]
@tiann https://github.com/android-hacker/VirtualXposed/releases/tag/0.17.2 Only one APK.

**Comment by tiann** [comment]
@Enyby I am sorry, I will add it soon.
