### ISSUE TITLE
Missing QQ number in 0.9.8 about screen

### ISSUE THREAD

**Issue by Enyby** [android-hacker/VirtualXposed#81]
![scr_1524225217](https://user-images.githubusercontent.com/1543372/39049584-c21f85f6-44aa-11e8-99a4-14b40470cd9b.jpg)

**Comment by tiann** [comment]
click the QQ group, the qq number will be put in your clipboard.

UI will be be fixed in next release.

**Comment by tiann** [comment]
fixed: https://github.com/android-hacker/VirtualXposed/commit/e0b6f6358ea8e93cff89adf3cf77b038d85efb76
