### ISSUE TITLE
VXP中的QQ 微信会频繁闪退

### ISSUE THREAD

**Issue by phone-burner** [android-hacker/VirtualXposed#813]
## 问题描述
VXP中的QQ 微信会频繁闪退
## 复现步骤
无（正常打开VXP启动应用）
## 环境

机型：米6X
系统版本：MIUI 10/11 Android 8.1/9
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）都试过
Xposed 插件以及插件版本：
VirtualXposed版本：0.17.1及后续版本
## 补充
从系统反馈来看，应该是这两个应用故意闪退
系统报错null pointer reference，我差点以为硬件坏了，用了EdXposed才发现是VXP的锅。

**Comment by ChenFeya** [comment]
微信中的lib没有copy到vxp下，导致运行时闪退，然后系统报了一堆空指针，根本原因是微信版本升级了，apk下没有32位的so。

**Comment by Ayu8806** [comment]
机型：华为畅享9
系统版本：EMUI :8.2.0    Android：8.1.0
VirtualXposed版本：0.18.1/0.18.2
出现的问题：打开com.tencent.mm失败。或者微信一直卡在登录加载中，或者点击登录 就返回到输入密码界面。
