### ISSUE TITLE
VirtualXposed正在运行  任务栏的提醒能去掉吗？

### ISSUE THREAD

**Issue by tpnet** [android-hacker/VirtualXposed#86]
![screenshot](https://user-images.githubusercontent.com/17380722/39113224-8d6e927e-470d-11e8-881d-396c06b520ea.jpg)

**Comment by tiann** [comment]
去掉之后，进程容易被系统杀死，导致消息收不到。

Android 8.1 系统可以在设置中关闭这个系统通知。

**Comment by tpnet** [comment]
@tiann  android8.1关闭之后，微信消息那些也会不显示了啊啊啊

**Comment by tiann** [comment]
不是让你整个关掉APP的通知，而是关闭系统的那个提示。

https://jingyan.baidu.com/article/afd8f4deb372fa34e286e931.html
