### ISSUE TITLE
能否提供共享文件空间？

### ISSUE THREAD

**Issue by captain-miao** [android-hacker/VirtualXposed#87]
悟空加速/上帝模式/应用管理Xposed 模块，规则都是通过文件来共享的，其他应用可以读取到。

之前使用的是 ContentProvider 方式来共享，但是不同手机上服务稳定性很差。

希望可以提供：
1. Xposed 模块可以判断当前是否 VirtualXposed 环境
2. Xposed 模块可以读取/保存文件，类似共享空间

谢谢～

**Comment by tiann** [comment]
> 之前使用的是 ContentProvider 方式来共享，但是不同手机上服务稳定性很差

 这个是VXP特有的问题还是Xposed本身也有？还有，在Xposed框架中，你们是如何处理这种问题的？（XSharedPreference是否可以满足要求？又或者应用变量是直接存SD卡的，这样有啥问题不？

**Comment by captain-miao** [comment]
1.  ContentProvider 是在手机系统上出现很多服务未启动，所以与 Xposed 和 VXP 无关；

2. XSharedPreference 在 Android 7.0 上不能(MODE_WORLD_READABLE)使用了，也不适合存 XSharedPreference 中；

3. 直接存SD卡也不能满足，有些应用没有读取存储的权限；

4. 目前是通过读取 777 权限的文件目录来实现的，设置 777 权限是需要 root ；

**Comment by tiann** [comment]
目前在VXP内部，一定是有权限访问SD卡的（XSharedPreference也可以直接使用）。

目前在root情况下，是把文件放在内部存储的某个777目录？如果是这样的话，可以通过判断能否访问此文件判断是否处于VXP环境。

> Xposed 模块可以判断当前是否 VirtualXposed 环境
如果这个确实是必要的话，我可以加一个环境变量(System.setProperty)。但是考虑到可能某些应用以后可能会有环境检测，加入这个会带来不必要的麻烦。

**Comment by captain-miao** [comment]
好的，那么可以做 VXP 的兼容处理了～

> 如果这个确实是必要的话，我可以加一个环境变量(System.setProperty)。但是考虑到某些应用以后可能会有环境检测，加入这个会带来不必要的麻烦。

还是建议加入，相当于有一个官方可靠的判断；

**Comment by tiann** [comment]
已经加上了，可以用如下方式判断：`System.getProperty("vxp") != null`。

**Comment by tiann** [comment]
文档已更新：[Xposed 和 VirtualXposed 的区别](https://github.com/android-hacker/VirtualXposed/wiki/Difference-between-Xposed-and-VirtualXposed)
