### ISSUE TITLE
Failed to run at 360N4S

### ISSUE THREAD

**Issue by vanishcode** [android-hacker/VirtualXposed#9]
![screenshot_2018-03-12-12-04-45](https://user-images.githubusercontent.com/20496444/37265356-bfd4695a-25ed-11e8-8234-71fdc728be17.png)

试玩失败(ಥ_ಥ)，就是没有任何效果，比如微信支付，重启爪机也不好使
不太懂这个，不知道什么原因。。

**Comment by tiann** [comment]
具体“试玩”的什么功能？
支付功能比较特殊，现在是不支持的。

**Comment by vanishcode** [comment]
嗖嘎，了解了~持续关注~
