### ISSUE TITLE
建议：系统添加应用改名功能，可以发送到主桌面

### ISSUE THREAD

**Issue by niluanxy** [android-hacker/VirtualXposed#93]
比如我在 virtualxposed 里装两个微信，然后创建桌面快捷方式，结果名字很丑，希望能添加个自定义的功能，这样就完美了

**Comment by tiann** [comment]
有需要自己改代码。

**Comment by niluanxy** [comment]
能说下大概位置吗，虽然是个程序员，但对安卓不是太懂

**Comment by tiann** [comment]
添加快捷方式的函数：com.lody.virtual.client.core.VirtualCore#createShortcut(int, java.lang.String, android.content.Intent, com.lody.virtual.client.core.VirtualCore.OnEmitShortcutListener)

长按弹出菜单的事件：com.android.launcher3.popup.SystemShortcut.CreateDesktopShortcut
