### ISSUE TITLE
Google play services

### ISSUE THREAD

**Issue by ayhamo** [android-hacker/VirtualXposed#94]
Hi mate, last time i asked for your help you was really helpfully, now i need it again, 
Ita not an issue really its just will you release Google play services , or just "google play games " so w3 can connect to it.
Thanks in advance and keep the amazing work.
Just a question, does xposed modules affect real phone or just the emulator?!

**Comment by tiann** [comment]
1. Google play service is working in progress.
2. Xposed module in VirtualXposed has no any effect on real phone, but if you install Xposed by rovo89  in your system, it may affect VirtualXposed.

**Comment by ayhamo** [comment]
Any ETA on Google play service?!

No , my phone has no root and installed it from here, link you provided when you fixed oreo issue

**Comment by tiann** [comment]
No ETA, I do it in spare time, I am not sure when i can finish it.

**Comment by mehedihasanrj** [comment]
![screenshot_20180507-185024](https://user-images.githubusercontent.com/39218757/39958286-d53f633e-5622-11e8-83e7-81c6634fc7fb.png)
![screenshot_20180507-184820](https://user-images.githubusercontent.com/39218757/39958291-e05b8fea-5622-11e8-96ed-ff0a67f74c70.png)

I can not do many things without Google Play Service. Opening on many apps and games comes the text "Google Play does not support your phone" and it exits apps and games. So I think Google Play Service needs to be added very quickly. Thank You.

There are some screenshots here

**Comment by tiann** [comment]
fixed https://github.com/android-hacker/VirtualXposed/commit/0d27afb88f77abae658b060d9c396816fd1e12e4
