### ISSUE TITLE
广东移动app不能卡在启动页面

### ISSUE THREAD

**Issue by zhuangdx** [android-hacker/VirtualXposed#98]
把广东移动app丢到virtualxposed中启动，安装后第一次启动有app介绍页面，但一直卡在启动面。不知道怎么查看。最新的virtualxposed  0.9.8
![screenshot_20180428-161637](https://user-images.githubusercontent.com/16098983/39394051-98cee04c-4aff-11e8-9dd6-7e5b5fd99b0e.png)

**Comment by tiann** [comment]
此APP使用了 360加固，暂不支持。也没有计划支持。
