### ISSUE TITLE
可以设置app安装到sd卡么？

### ISSUE THREAD

**Issue by scskarsper** [android-hacker/VirtualXposed#99]
RT，现在沙盒程序是装在/sdcard/virtualxposed/vsexposed下的。但是早一点的手机（红米3 16GB）。默认存储已经很小了。像百度地图、淘宝京东之类的只有偶尔用用的程序完全可以放到tf卡里。虽然link2sd什么的也许可以。但是很显然miui什么的不行。是不是可以在高级设置里添加一个设置配置沙盒的根目录到/storage/{tf卡}/virtualxposed或者某个自定义目录呢？

**Comment by tiann** [comment]
存储空间越来越大是趋势，没必要也没有精力去为了这个开发新功能。

**Comment by qqzwc** [comment]
> 存储空间越来越大是趋势，没必要也没有精力去为了这个开发新功能。

并不完全是这样，存在内部存储的优势是，可以防止恢复出厂设置后内部沙盒程序丢失
